import type { TemplateFile } from "../types";
import { lines } from "../utils/lines";

/**
 * Generate UI template files for the "login-tabs" preset.
 * Includes: Sign-in page, 3-tab layout (Home/List/Mine),
 * Home page with Button & AlertDialog demos, Mine page with sign-out.
 */
export function generateLoginTabsTemplates(projectName: string): TemplateFile[] {
  return [
    // ─── app/_layout.tsx (overwrite base) ────────────────────────────────
    {
      path: "app/_layout.tsx",
      content: lines(
        'import { DarkTheme, DefaultTheme, ThemeProvider } from "@react-navigation/native";',
        'import { useFonts } from "expo-font";',
        'import { Stack } from "expo-router";',
        'import * as SplashScreen from "expo-splash-screen";',
        'import { useEffect } from "react";',
        'import { useColorScheme } from "react-native";',
        "",
        'import { Colors } from "@/constants/Colors";',
        "",
        "SplashScreen.preventAutoHideAsync();",
        "",
        "export default function RootLayout() {",
        "  const colorScheme = useColorScheme();",
        "  const [loaded] = useFonts({",
        "    SpaceMono: require(\"../assets/fonts/SpaceMono-Regular.ttf\"),",
        "  });",
        "",
        "  useEffect(() => {",
        "    if (loaded) {",
        "      SplashScreen.hideAsync();",
        "    }",
        "  }, [loaded]);",
        "",
        "  if (!loaded) {",
        "    return null;",
        "  }",
        "",
        "  return (",
        "    <ThemeProvider value={colorScheme === \"dark\" ? DarkTheme : DefaultTheme}>",
        "      <Stack>",
        '        <Stack.Screen name="login" options={{ headerShown: false }} />',
        '        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />',
        '        <Stack.Screen name="+not-found" />',
        "      </Stack>",
        "    </ThemeProvider>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── app/login.tsx ───────────────────────────────────────────────────
    {
      path: "app/login.tsx",
      content: lines(
        'import { SignInForm } from "@/components/SignInForm";',
        'import { View } from "react-native";',
        "",
        "export default function LoginScreen() {",
        "  return (",
        '    <View className="flex-1 items-center justify-center p-4">',
        "      <SignInForm />",
        "    </View>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── app/(tabs)/_layout.tsx (overwrite base) ───────────────────────
    {
      path: "app/(tabs)/_layout.tsx",
      content: lines(
        'import { Tabs } from "expo-router";',
        'import { Platform } from "react-native";',
        "",
        'import { Colors } from "@/constants/Colors";',
        'import { useColorScheme } from "@/hooks/useColorScheme";',
        "",
        "export default function TabLayout() {",
        "  const colorScheme = useColorScheme();",
        "",
        "  return (",
        "    <Tabs",
        "      screenOptions={{",
        "        tabBarActiveTintColor: Colors[colorScheme ?? \"light\"].tint,",
        "        headerStyle: {",
        "          backgroundColor: Colors[colorScheme ?? \"light\"].background,",
        "        },",
        "        headerShadowVisible: false,",
        "        tabBarStyle: Platform.select({",
        "          ios: {",
        "            position: \"absolute\",",
        "          },",
        "          default: {},",
        "        }),",
        "      }}",
        "    >",
        "      <Tabs.Screen",
        '        name="home"',
        "        options={{",
        '          title: "Home",',
        "          tabBarIcon: () => null,",
        "        }}",
        "      />",
        "      <Tabs.Screen",
        '        name="list"',
        "        options={{",
        '          title: "List",',
        "          tabBarIcon: () => null,",
        "        }}",
        "      />",
        "      <Tabs.Screen",
        '        name="mine"',
        "        options={{",
        '          title: "Mine",',
        "          tabBarIcon: () => null,",
        "        }}",
        "      />",
        "    </Tabs>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── app/(tabs)/home.tsx ────────────────────────────────────────────
    {
      path: "app/(tabs)/home.tsx",
      content: lines(
        'import { Button } from "@/components/ui/button";',
        'import {',
        '  AlertDialog,',
        '  AlertDialogAction,',
        '  AlertDialogCancel,',
        '  AlertDialogContent,',
        '  AlertDialogDescription,',
        '  AlertDialogFooter,',
        '  AlertDialogHeader,',
        '  AlertDialogTitle,',
        '  AlertDialogTrigger,',
        '} from "@/components/ui/alert-dialog";',
        'import { Text } from "@/components/ui/text";',
        'import { View } from "react-native";',
        "",
        "export default function HomeScreen() {",
        "  return (",
        '    <View className="flex-1 gap-6 p-6">',
        "      <Text variant=\"h3\">UI Components</Text>",
        "      <Text variant=\"muted\">React Native Reusables components showcase</Text>",
        "",
        "      {/* Button variants */}",
        '      <View className="gap-3">',
        '        <Text variant="large">Buttons</Text>',
        "        <View className=\"flex-row flex-wrap gap-2\">",
        '          <Button onPress={() => {}}>',
        '            <Text>Default</Text>',
        "          </Button>",
        '          <Button variant="secondary" onPress={() => {}}>',
        '            <Text>Secondary</Text>',
        "          </Button>",
        '          <Button variant="destructive" onPress={() => {}}>',
        '            <Text>Destructive</Text>',
        "          </Button>",
        '          <Button variant="outline" onPress={() => {}}>',
        '            <Text>Outline</Text>',
        "          </Button>",
        '          <Button variant="ghost" onPress={() => {}}>',
        '            <Text>Ghost</Text>',
        "          </Button>",
        '          <Button variant="link" onPress={() => {}}>',
        '            <Text>Link</Text>',
        "          </Button>",
        "        </View>",
        "      </View>",
        "",
        "      {/* AlertDialog */}",
        '      <View className="gap-3">',
        '        <Text variant="large">Alert Dialog</Text>',
        "        <AlertDialog>",
        "          <AlertDialogTrigger asChild>",
        '            <Button variant="outline">',
        '              <Text>Show Alert</Text>',
        "            </Button>",
        "          </AlertDialogTrigger>",
        "          <AlertDialogContent>",
        "            <AlertDialogHeader>",
        '              <AlertDialogTitle>Are you sure?</AlertDialogTitle>',
        "              <AlertDialogDescription>",
        "                This action cannot be undone. This will permanently delete your account and remove your data from our servers.",
        "              </AlertDialogDescription>",
        "            </AlertDialogHeader>",
        "            <AlertDialogFooter>",
        "              <AlertDialogCancel>",
        '                <Text>Cancel</Text>',
        "              </AlertDialogCancel>",
        "              <AlertDialogAction>",
        '                <Text>Continue</Text>',
        "              </AlertDialogAction>",
        "            </AlertDialogFooter>",
        "          </AlertDialogContent>",
        "        </AlertDialog>",
        "      </View>",
        "    </View>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── app/(tabs)/list.tsx ────────────────────────────────────────────
    {
      path: "app/(tabs)/list.tsx",
      content: lines(
        'import { Text } from "@/components/ui/text";',
        'import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";',
        'import { View, ScrollView } from "react-native";',
        "",
        "const ITEMS = Array.from({ length: 20 }, (_, i) => ({",
        "  id: String(i + 1),",
        "  title: `Item ${i + 1}`,",
        "  description: `Description for item ${i + 1}`,",
        "}));",
        "",
        "export default function ListScreen() {",
        "  return (",
        '    <ScrollView className="flex-1 p-4">',
        '      <Text variant="h3" className="mb-4">List</Text>',
        '      <View className="gap-3">',
        "        {ITEMS.map((item) => (",
        '          <Card key={item.id}>',
        "            <CardHeader>",
        "              <CardTitle>{item.title}</CardTitle>",
        "              <CardDescription>{item.description}</CardDescription>",
        "            </CardHeader>",
        "            <CardContent />",
        "          </Card>",
        "        ))}",
        "      </View>",
        "    </ScrollView>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── app/(tabs)/mine.tsx ────────────────────────────────────────────
    {
      path: "app/(tabs)/mine.tsx",
      content: lines(
        'import { Button } from "@/components/ui/button";',
        'import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";',
        'import { Text } from "@/components/ui/text";',
        'import { View } from "react-native";',
        'import { router } from "expo-router";',
        "",
        "export default function MineScreen() {",
        "  return (",
        '    <View className="flex-1 p-6">',
        '      <Text variant="h3" className="mb-6">Mine</Text>',
        "",
        '      <Card className="mb-6">',
        '        <CardHeader>',
        '          <CardTitle>Profile</CardTitle>',
        "        </CardHeader>",
        "        <CardContent>",
        '          <View className="gap-2">',
        '            <Text variant="muted">User Name</Text>',
        '            <Text>user@example.com</Text>',
        "          </View>",
        "        </CardContent>",
        "      </Card>",
        "",
        '      <Button',
        '        variant="destructive"',
        "        className=\"w-full\"",
        "        onPress={() => {",
        '          router.replace("/login");',
        "        }}",
        "      >",
        '        <Text>Sign Out</Text>',
        "      </Button>",
        "    </View>",
        "  );",
        "}",
        ""
      ),
    },

    // ─── src/components/SignInForm.tsx ───────────────────────────────────
    {
      path: "components/SignInForm.tsx",
      content: lines(
        'import { Button } from "@/components/ui/button";',
        'import {',
        '  Card,',
        '  CardContent,',
        '  CardDescription,',
        '  CardHeader,',
        '  CardTitle,',
        '} from "@/components/ui/card";',
        'import { Input } from "@/components/ui/input";',
        'import { Label } from "@/components/ui/label";',
        'import { Separator } from "@/components/ui/separator";',
        'import { Text } from "@/components/ui/text";',
        'import * as React from "react";',
        'import { Pressable, type TextInput, View } from "react-native";',
        'import { router } from "expo-router";',
        "",
        "export function SignInForm() {",
        "  const passwordInputRef = React.useRef<TextInput>(null);",
        "",
        "  function onEmailSubmitEditing() {",
        "    passwordInputRef.current?.focus();",
        "  }",
        "",
        "  function onSubmit() {",
        "    // TODO: Submit form and navigate to protected screen if successful",
        '    router.replace("/(tabs)/home");',
        "  }",
        "",
        "  return (",
        '    <View className="gap-6 w-full max-w-sm">',
        '      <Card className="shadow-none sm:shadow-sm sm:shadow-black/5">',
        "        <CardHeader>",
        '          <CardTitle className="text-center text-xl sm:text-left">Sign in to your app</CardTitle>',
        '          <CardDescription className="text-center sm:text-left">',
        "            Welcome back! Please sign in to continue",
        "          </CardDescription>",
        "        </CardHeader>",
        '        <CardContent className="gap-6">',
        '          <View className="gap-6">',
        '            <View className="gap-1.5">',
        '              <Label nativeID="email">Email</Label>',
        "              <Input",
        '                placeholder="m@example.com"',
        '                keyboardType="email-address"',
        '                autoComplete="email"',
        '                autoCapitalize="none"',
        "                onSubmitEditing={onEmailSubmitEditing}",
        '                returnKeyType="next"',
        '                submitBehavior="submit"',
        "              />",
        "            </View>",
        '            <View className="gap-1.5">',
        '              <View className="flex-row items-center">',
        '                <Label nativeID="password">Password</Label>',
        "                <Button",
        '                  variant="link"',
        '                  size="sm"',
        '                  className="ml-auto h-4 px-1 py-0 sm:h-4"',
        "                  onPress={() => {",
        "                    // TODO: Navigate to forgot password screen",
        "                  }}",
        "                >",
        '                  <Text className="font-normal leading-4">Forgot your password?</Text>',
        "                </Button>",
        "              </View>",
        "              <Input",
        "                ref={passwordInputRef}",
        "                secureTextEntry",
        '                returnKeyType="send"',
        "                onSubmitEditing={onSubmit}",
        "              />",
        "            </View>",
        '            <Button className="w-full" onPress={onSubmit}>',
        '              <Text>Continue</Text>',
        "            </Button>",
        "          </View>",
        '          <Text className="text-center text-sm">',
        "            Don&apos;t have an account?{\" \"}",
        "            <Pressable",
        "              onPress={() => {",
        "                // TODO: Navigate to sign up screen",
        "              }}",
        "            >",
        '              <Text className="text-sm underline underline-offset-4">Sign up</Text>',
        "            </Pressable>",
        "          </Text>",
        '          <View className="flex-row items-center">',
        '            <Separator className="flex-1" />',
        '            <Text className="text-muted-foreground px-4 text-sm">or</Text>',
        '            <Separator className="flex-1" />',
        "          </View>",
        "        </CardContent>",
        "      </Card>",
        "    </View>",
        "  );",
        "}",
        ""
      ),
    },
  ];
}
