import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const authFacebookModule: ModuleDef = {
  id: "auth-facebook",
  name: "Facebook 登录",
  description: "expo-facebook",
  defaultChecked: false,
  dependencies: {
    "expo-facebook": "~13.0.0",
  },
  devDependencies: {},
  files: [
    {
      path: "modules/auth/facebook.ts",
      content: lines(
        'import * as Facebook from "expo-facebook";',
        "",
        "export interface FacebookAuthConfig {",
        "  appId: string;",
        "  appName: string;",
        "}",
        "",
        "export async function setupFacebookAuth(config: FacebookAuthConfig): Promise<void> {",
        "  await Facebook.initializeAsync({",
        "    appId: config.appId,",
        "    appName: config.appName,",
        "  });",
        "}",
        "",
        "export async function signInWithFacebook(): Promise<{",
        "  token: string | null;",
        "  userId: string | null;",
        "  userName: string | null;",
        "  error: string | null;",
        "}> {",
        "  try {",
        "    const result = await Facebook.logInWithReadPermissionsAsync({",
        '      permissions: ["public_profile", "email"],',
        "    });",
        "",
        '    if (result.type === "success") {',
        "      const response = await fetch(",
        '        `https://graph.facebook.com/me?access_token=${result.token}&fields=id,name,email`',
        "      );",
        "      const userData = await response.json();",
        "",
        "      return {",
        "        token: result.token,",
        "        userId: userData.id,",
        "        userName: userData.name,",
        "        error: null,",
        "      };",
        "    } else {",
        "      return {",
        "        token: null,",
        "        userId: null,",
        "        userName: null,",
        '        error: "用户取消了 Facebook 登录",',
        "      };",
        "    }",
        "  } catch (error) {",
        '    console.error("[FacebookAuth] Error:", error);',
        "    return {",
        "      token: null,",
        "      userId: null,",
        "      userName: null,",
        '      error: "Facebook 登录失败",',
        "    };",
        "  }",
        "}",
        "",
        "export async function signOutFacebook(): Promise<void> {",
        "  try {",
        "    await Facebook.logOutAsync();",
        "  } catch (error) {",
        '    console.error("[FacebookAuth] Sign out error:", error);',
        "  }",
        "}"
      ),
    },
  ],
  appConfig: {
    plugins: [
      [
        "expo-facebook",
        {
          appId: "YOUR_FACEBOOK_APP_ID",
        },
      ],
    ],
  },
};

export default authFacebookModule;
