import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const authGoogleModule: ModuleDef = {
  id: "auth-google",
  name: "Google 登录",
  description: "@react-native-google-signin/google-signin",
  defaultChecked: false,
  dependencies: {
    "@react-native-google-signin/google-signin": "^13.1.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/auth/google.ts",
      content: lines(
        'import {',
        "  GoogleSignin,",
        "  statusCodes,",
        "  type User,",
        '} from "@react-native-google-signin/google-signin";',
        "",
        "export interface GoogleAuthConfig {",
        "  iosClientId?: string;",
        "  webClientId?: string;",
        "  offlineAccess?: boolean;",
        "  forceCodeForRefreshToken?: boolean;",
        "}",
        "",
        "export function setupGoogleAuth(config: GoogleAuthConfig): void {",
        "  GoogleSignin.configure({",
        "    iosClientId: config.iosClientId,",
        "    webClientId: config.webClientId,",
        "    offlineAccess: config.offlineAccess ?? false,",
        "    forceCodeForRefreshToken: config.forceCodeForRefreshToken ?? true,",
        "  });",
        "}",
        "",
        "export async function signInWithGoogle(): Promise<{",
        "  user: User | null;",
        "  idToken: string | null;",
        "  error: string | null;",
        "}> {",
        "  try {",
        "    await GoogleSignin.hasPlayServices({",
        "      showPlayServicesUpdateDialog: true,",
        "    });",
        "",
        "    const userInfo = await GoogleSignin.signIn();",
        "    const idToken = userInfo.data?.idToken ?? null;",
        "",
        "    return {",
        "      user: userInfo.data ?? null,",
        "      idToken,",
        "      error: null,",
        "    };",
        "  } catch (error: any) {",
        '    let errorMessage = "Google 登录失败";',
        "",
        "    if (error.code === statusCodes.SIGN_IN_CANCELLED) {",
        '      errorMessage = "用户取消了登录";',
        "    } else if (error.code === statusCodes.IN_PROGRESS) {",
        '      errorMessage = "登录正在进行中";',
        "    } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {",
        '      errorMessage = "设备不支持 Google Play 服务";',
        "    }",
        "",
        '    console.error("[GoogleAuth] Error:", errorMessage, error);',
        "    return { user: null, idToken: null, error: errorMessage };",
        "  }",
        "}",
        "",
        "export async function signOutGoogle(): Promise<void> {",
        "  try {",
        "    await GoogleSignin.signOut();",
        "  } catch (error) {",
        '    console.error("[GoogleAuth] Sign out error:", error);',
        "  }",
        "}",
        "",
        "export async function getCurrentGoogleUser(): Promise<User | null> {",
        "  try {",
        "    const user = await GoogleSignin.getCurrentUser();",
        "    return user;",
        "  } catch {",
        "    return null;",
        "  }",
        "}",
        "",
        "export async function isGoogleSignedIn(): Promise<boolean> {",
        "  try {",
        "    return GoogleSignin.hasPreviousSignIn();",
        "  } catch {",
        "    return false;",
        "  }",
        "}"
      ),
    },
  ],
};

export default authGoogleModule;
