import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const authFacebookModule: ModuleDef = {
  id: "auth-facebook",
  name: "Facebook 登录",
  description: "expo-auth-session + expo-web-browser（SDK 54 不再支持 expo-facebook）",
  defaultChecked: false,
  dependencies: {
    "expo-auth-session": "~7.0.11",
    "expo-web-browser": "~15.0.11",
    "expo-crypto": "~15.0.9",
  },
  devDependencies: {},
  files: [
    {
      path: "modules/auth/facebook.ts",
      content: lines(
        'import { responseTypes } from "expo-auth-session";',
        'import { makeRedirectUri, useAuthRequest, useAutoDiscovery } from "expo-auth-session";',
        'import * as WebBrowser from "expo-web-browser";',
        "",
        "// Facebook OAuth 配置",
        "export interface FacebookAuthConfig {",
        "  clientId: string; // Facebook App ID",
        "}",
        "",
        "// Facebook OAuth 端点",
        "const FACEBOOK_AUTH_ENDPOINT = \"https://www.facebook.com/v18.0/dialog/oauth\";",
        "const FACEBOOK_TOKEN_ENDPOINT = \"https://graph.facebook.com/v18.0/oauth/access_token\";",
        "",
        "// 确保 WebBrowser 回调完成时关闭",
        "WebBrowser.maybeCompleteAuthSession();",
        "",
        "/**",
        " * 使用 expo-auth-session 实现 Facebook 登录",
        " *",
        " * 用法：",
        " * 1. 在 Facebook Developer Console 创建应用，获取 App ID",
        " * 2. 配置 OAuth 重定向 URI",
        " * 3. 在组件中使用 useFacebookAuth hook",
        " *",
        " * 注意：SDK 54 不再支持 expo-facebook，改用 expo-auth-session",
        " */",
        "",
        "export function useFacebookAuth(config: FacebookAuthConfig) {",
        "  const redirectUri = makeRedirectUri({",
        "    scheme: 'your-app-scheme', // 替换为你的 app scheme",
        "  });",
        "",
        "  const [request, response, promptAsync] = useAuthRequest(",
        "    {",
        "      clientId: config.clientId,",
        "      scopes: ['public_profile', 'email'],",
        "      redirectUri,",
        "    },",
        "    {",
        "      authorizationEndpoint: FACEBOOK_AUTH_ENDPOINT,",
        "      tokenEndpoint: FACEBOOK_TOKEN_ENDPOINT,",
        "    }",
        "  );",
        "",
        "  return { request, response, promptAsync };",
        "}",
        "",
        "/**",
        " * 从 Facebook OAuth 响应中提取用户信息",
        " */",
        "export async function getFacebookUserInfo(accessToken: string): Promise<{",
        "  userId: string;",
        "  userName: string;",
        "  email: string | null;",
        "}> {",
        "  const response = await fetch(",
        "    `https://graph.facebook.com/me?access_token=${accessToken}&fields=id,name,email`",
        "  );",
        "  const userData = await response.json();",
        "",
        "  return {",
        "    userId: userData.id,",
        "    userName: userData.name,",
        "    email: userData.email ?? null,",
        "  };",
        "}",
      ),
    },
  ],
  appConfig: {},
};

export default authFacebookModule;
