import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const authAppleModule: ModuleDef = {
  id: "auth-apple",
  name: "Apple 登录",
  description: "expo-apple-authentication",
  defaultChecked: false,
  dependencies: {
    "expo-apple-authentication": "~8.0.8",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/auth/apple.ts",
      content: lines(
        'import * as AppleAuthentication from "expo-apple-authentication";',
        'import { Platform } from "react-native";',
        "",
        "export interface AppleAuthResult {",
        "  user: string;",
        "  email: string | null;",
        "  fullName: AppleAuthentication.AppleAuthenticationFullName | null;",
        "  identityToken: string | null;",
        "  authorizationCode: string | null;",
        "  error: string | null;",
        "}",
        "",
        "export async function isAppleAuthAvailable(): Promise<boolean> {",
        '  if (Platform.OS !== "ios") return false;',
        "  return AppleAuthentication.isAvailableAsync();",
        "}",
        "",
        "export async function signInWithApple(): Promise<AppleAuthResult> {",
        "  try {",
        "    const credential = await AppleAuthentication.signInAsync({",
        "      requestedScopes: [",
        "        AppleAuthentication.AppleAuthenticationScope.FULL_NAME,",
        "        AppleAuthentication.AppleAuthenticationScope.EMAIL,",
        "      ],",
        "    });",
        "",
        "    return {",
        "      user: credential.user,",
        "      email: credential.email ?? null,",
        "      fullName: credential.fullName ?? null,",
        "      identityToken: credential.identityToken ?? null,",
        "      authorizationCode: credential.authorizationCode ?? null,",
        "      error: null,",
        "    };",
        "  } catch (error: any) {",
        '    if (error.code === "ERR_CANCELED") {',
        "      return {",
        '        user: "",',
        "        email: null,",
        "        fullName: null,",
        "        identityToken: null,",
        "        authorizationCode: null,",
        '        error: "用户取消了 Apple 登录",',
        "      };",
        "    }",
        "",
        '    console.error("[AppleAuth] Error:", error);',
        "    return {",
        '      user: "",',
        "      email: null,",
        "      fullName: null,",
        "      identityToken: null,",
        "      authorizationCode: null,",
        '      error: "Apple 登录失败",',
        "    };",
        "  }",
        "}",
        "",
        "export async function getAppleCredentialState(",
        "  userId: string",
        "): Promise<AppleAuthentication.AppleAuthenticationCredentialState> {",
        "  return AppleAuthentication.getCredentialStateAsync(userId);",
        "}",
        "",
        "export async function signOutApple(userId: string): Promise<boolean> {",
        "  try {",
        "    const state = await getAppleCredentialState(userId);",
        "    return state === AppleAuthentication.AppleAuthenticationCredentialState.REVOKED;",
        "  } catch {",
        "    return false;",
        "  }",
        "}"
      ),
    },
  ],
  appConfig: {
    plugins: ["expo-apple-authentication"],
  },
};

export default authAppleModule;
