import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const bottomSheetModule: ModuleDef = {
  id: "bottom-sheet",
  name: "Bottom Sheet",
  description: "@gorhom/bottom-sheet",
  defaultChecked: false,
  dependencies: {
    "@gorhom/bottom-sheet": "^5.1.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/components/AppBottomSheet.tsx",
      content: lines(
        'import React, { useCallback, useRef } from "react";',
        'import { View, Text, StyleSheet } from "react-native";',
        'import BottomSheet, {',
        "  BottomSheetBackdrop,",
        "  BottomSheetView,",
        "  type BottomSheetBackdropProps,",
        "  type BottomSheetProps,",
        '} from "@gorhom/bottom-sheet";',
        "",
        "interface AppBottomSheetProps extends Omit<BottomSheetProps, \"children\"> {",
        "  title?: string;",
        "  children: React.ReactNode;",
        "  onClose?: () => void;",
        "}",
        "",
        "export const AppBottomSheet = React.forwardRef<BottomSheet, AppBottomSheetProps>(",
        "  ({ title, children, onClose, snapPoints = [\"50%\"], ...rest }, ref) => {",
        "    const localRef = useRef<BottomSheet>(null);",
        "    const sheetRef = (ref as React.RefObject<BottomSheet>) || localRef;",
        "",
        "    const renderBackdrop = useCallback(",
        "      (props: BottomSheetBackdropProps) => (",
        "        <BottomSheetBackdrop",
        "          {...props}",
        "          disappearsOnIndex={-1}",
        "          appearsOnIndex={0}",
        '          pressBehavior="close"',
        "        />",
        "      ),",
        "      []",
        "    );",
        "",
        "    const handleSheetChange = useCallback(",
        "      (index: number) => {",
        "        if (index === -1 && onClose) {",
        "          onClose();",
        "        }",
        "      },",
        "      [onClose]",
        "    );",
        "",
        "    return (",
        "      <BottomSheet",
        "        ref={sheetRef}",
        "        index={-1}",
        "        snapPoints={snapPoints}",
        "        backdropComponent={renderBackdrop}",
        "        onChange={handleSheetChange}",
        "        enablePanDownToClose",
        "        backgroundStyle={styles.background}",
        "        handleIndicatorStyle={styles.handleIndicator}",
        "        {...rest}",
        "      >",
        "        <BottomSheetView style={styles.content}>",
        "          {title && <Text style={styles.title}>{title}</Text>}",
        "          {children}",
        "        </BottomSheetView>",
        "      </BottomSheet>",
        "    );",
        "  }",
        ");",
        "",
        'AppBottomSheet.displayName = "AppBottomSheet";',
        "",
        "const styles = StyleSheet.create({",
        "  background: {",
        "    borderRadius: 16,",
        "  },",
        "  handleIndicator: {",
        '    backgroundColor: "#d1d5db",',
        "    width: 40,",
        "  },",
        "  content: {",
        "    paddingHorizontal: 16,",
        "    paddingBottom: 24,",
        "  },",
        "  title: {",
        "    fontSize: 18,",
        '    fontWeight: "600",',
        '    color: "#1a1a1a",',
        "    marginBottom: 16,",
        "  },",
        "});",
        "",
        "export default AppBottomSheet;"
      ),
    },
  ],
  layoutProviders: ["<BottomSheetModalProvider>"],
  layoutImports: [
    'import { BottomSheetModalProvider } from "@gorhom/bottom-sheet";',
  ],
};

export default bottomSheetModule;
