import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const flashlistModule: ModuleDef = {
  id: "flashlist",
  name: "FlashList",
  description: "@shopify/flash-list",
  defaultChecked: false,
  dependencies: {
    "@shopify/flash-list": "2.0.2",
  },
  devDependencies: {},
  files: [
    {
      path: "components/AppFlashList.tsx",
      content: lines(
        'import React, { useCallback } from "react";',
        'import { View, Text, StyleSheet, type ListRenderItemInfo } from "react-native";',
        'import {',
        "  FlashList,",
        "  type FlashListProps,",
        '} from "@shopify/flash-list";',
        "",
        "export interface ListItem {",
        "  id: string;",
        "  [key: string]: unknown;",
        "}",
        "",
        "interface AppFlashListProps<T extends ListItem>",
        "  extends Omit<FlashListProps<T>, \"renderItem\" | \"estimatedItemSize\"> {",
        "  renderItem: (info: ListRenderItemInfo<T>) => React.ReactElement | null;",
        "  estimatedItemSize?: number;",
        "  ListEmptyComponent?: React.ReactElement;",
        "  isLoading?: boolean;",
        "  LoadingComponent?: React.ReactElement;",
        "}",
        "",
        "export function AppFlashList<T extends ListItem>({",
        "  data,",
        "  renderItem,",
        "  estimatedItemSize = 50,",
        "  ListEmptyComponent,",
        "  isLoading,",
        "  LoadingComponent,",
        "  ...rest",
        "}: AppFlashListProps<T>) {",
        "  const defaultEmptyComponent = React.useMemo(",
        "    () => (",
        "      <View style={styles.emptyContainer}>",
        '        <Text style={styles.emptyText}>暂无数据</Text>',
        "      </View>",
        "    ),",
        "    []",
        "  );",
        "",
        "  const defaultLoadingComponent = React.useMemo(",
        "    () => (",
        "      <View style={styles.loadingContainer}>",
        '        <Text style={styles.loadingText}>加载中...</Text>',
        "      </View>",
        "    ),",
        "    []",
        "  );",
        "",
        "  if (isLoading) {",
        "    return LoadingComponent ?? defaultLoadingComponent;",
        "  }",
        "",
        "  return (",
        "    <FlashList",
        "      data={data}",
        "      renderItem={renderItem}",
        "      estimatedItemSize={estimatedItemSize}",
        "      ListEmptyComponent={ListEmptyComponent ?? defaultEmptyComponent}",
        "      drawDistance={200}",
        "      {...rest}",
        "    />",
        "  );",
        "}",
        "",
        "const styles = StyleSheet.create({",
        "  emptyContainer: {",
        "    flex: 1,",
        "    justifyContent: \"center\",",
        "    alignItems: \"center\",",
        "    paddingVertical: 40,",
        "  },",
        "  emptyText: {",
        "    fontSize: 16,",
        '    color: "#999",',
        "  },",
        "  loadingContainer: {",
        "    flex: 1,",
        "    justifyContent: \"center\",",
        "    alignItems: \"center\",",
        "    paddingVertical: 40,",
        "  },",
        "  loadingText: {",
        "    fontSize: 16,",
        '    color: "#999",',
        "  },",
        "});",
        "",
        "export default AppFlashList;"
      ),
    },
  ],
};

export default flashlistModule;
