import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const formModule: ModuleDef = {
  id: "form",
  name: "表单验证",
  description: "React Hook Form + Zod",
  defaultChecked: false,
  dependencies: {
    "react-hook-form": "^7.54.0",
    "@hookform/resolvers": "^3.9.0",
    zod: "^3.24.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/form/index.ts",
      content: lines(
        'export { useForm } from "react-hook-form";',
        'export { z } from "zod";',
        'export { zodResolver } from "@hookform/resolvers/zod";',
        'export * from "./schemas/auth";'
      ),
    },
    {
      path: "src/modules/form/schemas/auth.ts",
      content: lines(
        'import { z } from "zod";',
        "",
        "export const loginSchema = z.object({",
        "  email: z",
        '    .string()',
        '    .min(1, "请输入邮箱地址")',
        '    .email("请输入有效的邮箱地址"),',
        "  password: z",
        '    .string()',
        '    .min(6, "密码至少6位")',
        '    .max(50, "密码最多50位"),',
        "});",
        "",
        "export const registerSchema = z",
        "  .object({",
        "    name: z",
        '      .string()',
        '      .min(2, "姓名至少2个字符")',
        '      .max(50, "姓名最多50个字符"),',
        "    email: z",
        '      .string()',
        '      .min(1, "请输入邮箱地址")',
        '      .email("请输入有效的邮箱地址"),',
        "    password: z",
        '      .string()',
        '      .min(6, "密码至少6位")',
        '      .max(50, "密码最多50位"),',
        '    confirmPassword: z.string().min(1, "请确认密码"),',
        "  })",
        "  .refine((data) => data.password === data.confirmPassword, {",
        '    message: "两次密码输入不一致",',
        '    path: ["confirmPassword"],',
        "  });",
        "",
        "export const resetPasswordSchema = z.object({",
        "  email: z",
        '    .string()',
        '    .min(1, "请输入邮箱地址")',
        '    .email("请输入有效的邮箱地址"),',
        "});",
        "",
        "export const changePasswordSchema = z",
        "  .object({",
        '    currentPassword: z.string().min(1, "请输入当前密码"),',
        "    newPassword: z",
        '      .string()',
        '      .min(6, "新密码至少6位")',
        '      .max(50, "新密码最多50位"),',
        '    confirmPassword: z.string().min(1, "请确认新密码"),',
        "  })",
        "  .refine((data) => data.newPassword === data.confirmPassword, {",
        '    message: "两次密码输入不一致",',
        '    path: ["confirmPassword"],',
        "  });",
        "",
        "export type LoginFormData = z.infer<typeof loginSchema>;",
        "export type RegisterFormData = z.infer<typeof registerSchema>;",
        "export type ResetPasswordFormData = z.infer<typeof resetPasswordSchema>;",
        "export type ChangePasswordFormData = z.infer<typeof changePasswordSchema>;"
      ),
    },
  ],
};

export default formModule;
