import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const imageModule: ModuleDef = {
  id: "image",
  name: "图片",
  description: "expo-image 封装",
  defaultChecked: false,
  dependencies: {
    "expo-image": "~3.0.11",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/media/CachedImage.tsx",
      content: lines(
        'import React, { useMemo } from "react";',
        'import { Image, type ImageProps } from "expo-image";',
        'import { StyleSheet, View, ActivityIndicator } from "react-native";',
        "",
        "interface CachedImageProps extends Omit<ImageProps, \"source\"> {",
        "  uri: string;",
        "  width?: number;",
        "  height?: number;",
        "  borderRadius?: number;",
        '  placeholderColor?: string;',
        "  showLoading?: boolean;",
        "}",
        "",
        "export function CachedImage({",
        "  uri,",
        "  width,",
        "  height,",
        "  borderRadius,",
        '  placeholderColor = "#f0f0f0",',
        "  showLoading = true,",
        "  style,",
        "  ...rest",
        "}: CachedImageProps) {",
        "  const containerStyle = useMemo(",
        "    () =>",
        "      StyleSheet.compose(",
        "        {",
        "          width,",
        "          height,",
        "          borderRadius,",
        "          backgroundColor: placeholderColor,",
        "          overflow: \"hidden\",",
        "        },",
        "        style as any",
        "      ),",
        "    [width, height, borderRadius, placeholderColor, style]",
        "  );",
        "",
        "  return (",
        "    <View style={containerStyle}>",
        "      <Image",
        "        source={{ uri }}",
        "        style={StyleSheet.absoluteFillObject}",
        '        contentFit="cover"',
        "        transition={200}",
        "        placeholder={{",
        '          blurhash: "LEHV6nWB2yk8pyo0adR*.7kCMdnj",',
        "        }}",
        "        {...rest}",
        "      />",
        "      {showLoading && (",
        "        <Image.LoadingIndicatorContainer",
        "          style={StyleSheet.absoluteFillObject}",
        "        >",
        '          <ActivityIndicator color="#999" />',
        "        </Image.LoadingIndicatorContainer>",
        "      )}",
        "    </View>",
        "  );",
        "}",
        "",
        "export default CachedImage;"
      ),
    },
  ],
};

export default imageModule;
