import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const networkModule: ModuleDef = {
  id: "network",
  name: "网络请求",
  description: "TanStack Query 封装，统一拦截器、错误处理",
  defaultChecked: true,
  dependencies: {
    "@tanstack/react-query": "^5.60.0",
  },
  devDependencies: {},
  files: [
    {
      path: "api/client.ts",
      content: lines(
        'import { Alert } from "react-native";',
        "",
        'const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || "https://api.example.com";',
        "",
        "interface RequestConfig {",
        '  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";',
        "  url: string;",
        "  data?: unknown;",
        "  headers?: Record<string, string>;",
        "  params?: Record<string, string>;",
        "}",
        "",
        "interface ApiResponse<T> {",
        "  data: T;",
        "  message: string;",
        "  code: number;",
        "}",
        "",
        "class ApiClient {",
        "  private baseUrl: string;",
        "  private defaultHeaders: Record<string, string>;",
        "  private requestInterceptors: Array<(config: RequestConfig) => RequestConfig> = [];",
        "  private responseInterceptors: Array<(response: Response) => Response> = [];",
        "",
        "  constructor(baseUrl: string) {",
        "    this.baseUrl = baseUrl;",
        "    this.defaultHeaders = {",
        '      "Content-Type": "application/json",',
        '      Accept: "application/json",',
        "    };",
        "  }",
        "",
        "  /** Add a request interceptor */",
        "  addRequestInterceptor(interceptor: (config: RequestConfig) => RequestConfig): void {",
        "    this.requestInterceptors.push(interceptor);",
        "  }",
        "",
        "  /** Add a response interceptor */",
        "  addResponseInterceptor(interceptor: (response: Response) => Response): void {",
        "    this.responseInterceptors.push(interceptor);",
        "  }",
        "",
        "  /** Set the authorization token */",
        "  setAuthToken(token: string): void {",
        '    this.defaultHeaders["Authorization"] = `Bearer ${token}`;',
        "  }",
        "",
        "  /** Clear the authorization token */",
        "  clearAuthToken(): void {",
        '    delete this.defaultHeaders["Authorization"];',
        "  }",
        "",
        "  /** Apply request interceptors */",
        "  private applyRequestInterceptors(config: RequestConfig): RequestConfig {",
        "    return this.requestInterceptors.reduce(",
        "      (acc, interceptor) => interceptor(acc),",
        "      config",
        "    );",
        "  }",
        "",
        "  /** Build URL with query params */",
        "  private buildUrl(url: string, params?: Record<string, string>): string {",
        "    const fullUrl = new URL(url, this.baseUrl);",
        "    if (params) {",
        '      Object.entries(params).forEach(([key, value]) => {',
        "        fullUrl.searchParams.append(key, value);",
        "      });",
        "    }",
        "    return fullUrl.toString();",
        "  }",
        "",
        "  /** Core request method */",
        "  async request<T>(config: RequestConfig): Promise<ApiResponse<T>> {",
        "    const interceptedConfig = this.applyRequestInterceptors(config);",
        "    const url = this.buildUrl(interceptedConfig.url, interceptedConfig.params);",
        "",
        "    try {",
        "      const response = await fetch(url, {",
        "        method: interceptedConfig.method,",
        "        headers: {",
        "          ...this.defaultHeaders,",
        "          ...interceptedConfig.headers,",
        "        },",
        "        body: interceptedConfig.data",
        "          ? JSON.stringify(interceptedConfig.data)",
        "          : undefined,",
        "      });",
        "",
        "      if (!response.ok) {",
        "        const errorData = await response.json().catch(() => null);",
        "        throw new ApiError(",
        "          response.status,",
        "          errorData?.message || response.statusText,",
        "          errorData",
        "        );",
        "      }",
        "",
        "      const data: ApiResponse<T> = await response.json();",
        "      return data;",
        "    } catch (error) {",
        "      if (error instanceof ApiError) {",
        "        throw error;",
        "      }",
        '      throw new ApiError(0, "网络请求失败，请检查网络连接", null);',
        "    }",
        "  }",
        "",
        "  /** GET request */",
        "  async get<T>(url: string, params?: Record<string, string>): Promise<ApiResponse<T>> {",
        '    return this.request<T>({ method: "GET", url, params });',
        "  }",
        "",
        "  /** POST request */",
        "  async post<T>(url: string, data?: unknown): Promise<ApiResponse<T>> {",
        '    return this.request<T>({ method: "POST", url, data });',
        "  }",
        "",
        "  /** PUT request */",
        "  async put<T>(url: string, data?: unknown): Promise<ApiResponse<T>> {",
        '    return this.request<T>({ method: "PUT", url, data });',
        "  }",
        "",
        "  /** PATCH request */",
        "  async patch<T>(url: string, data?: unknown): Promise<ApiResponse<T>> {",
        '    return this.request<T>({ method: "PATCH", url, data });',
        "  }",
        "",
        "  /** DELETE request */",
        "  async delete<T>(url: string): Promise<ApiResponse<T>> {",
        '    return this.request<T>({ method: "DELETE", url });',
        "  }",
        "}",
        "",
        "/** Custom API error class */",
        "export class ApiError extends Error {",
        "  code: number;",
        "  detail: unknown;",
        "",
        "  constructor(code: number, message: string, detail: unknown) {",
        "    super(message);",
        '    this.name = "ApiError";',
        "    this.code = code;",
        "    this.detail = detail;",
        "  }",
        "}",
        "",
        "/** Global error handler */",
        "export function handleApiError(error: unknown): void {",
        "  if (error instanceof ApiError) {",
        "    if (error.code === 401) {",
        '      Alert.alert("认证失败", "请重新登录");',
        "    } else if (error.code === 403) {",
        '      Alert.alert("权限不足", "您没有权限执行此操作");',
        "    } else if (error.code === 0) {",
        '      Alert.alert("网络错误", error.message);',
        "    } else {",
        '      Alert.alert("请求失败", error.message);',
        "    }",
        "  } else {",
        '    Alert.alert("未知错误", "请稍后重试");',
        "  }",
        "}",
        "",
        "/** Singleton API client instance */",
        "export const apiClient = new ApiClient(API_BASE_URL);",
        "",
        "export default apiClient;"
      ),
    },
    {
      path: "api/interceptors.ts",
      content: lines(
        'import type { RequestConfig } from "./client";',
        'import { apiClient } from "./client";',
        "",
        "/**",
        " * Initialize all request interceptors.",
        " * Called once during app startup.",
        " */",
        "export function setupRequestInterceptors(): void {",
        "  apiClient.addRequestInterceptor((config: RequestConfig) => {",
        "    return config;",
        "  });",
        "",
        "  if (__DEV__) {",
        "    apiClient.addRequestInterceptor((config: RequestConfig) => {",
        "      console.log(",
        '        `[API Request] ${config.method} ${config.url}`,',
        '        config.data ? config.data : ""',
        "      );",
        "      return config;",
        "    });",
        "  }",
        "}",
        "",
        "/**",
        " * Initialize all response interceptors.",
        " * Called once during app startup.",
        " */",
        "export function setupResponseInterceptors(): void {",
        "  if (__DEV__) {",
        "    apiClient.addResponseInterceptor((response: Response) => {",
        '      console.log(`[API Response] ${response.status} ${response.url}`);',
        "      return response;",
        "    });",
        "  }",
        "}",
        "",
        "/**",
        " * Setup all interceptors at once.",
        " */",
        "export function setupInterceptors(): void {",
        "  setupRequestInterceptors();",
        "  setupResponseInterceptors();",
        "}"
      ),
    },
    {
      path: "api/types.ts",
      content: lines(
        "/** Common API response types */",
        "",
        "/** Paginated response wrapper */",
        "export interface PaginatedResponse<T> {",
        "  data: T[];",
        "  total: number;",
        "  page: number;",
        "  pageSize: number;",
        "  totalPages: number;",
        "}",
        "",
        "/** Standard API response */",
        "export interface ApiResponse<T> {",
        "  data: T;",
        "  message: string;",
        "  code: number;",
        "}",
        "",
        "/** Common error response */",
        "export interface ErrorResponse {",
        "  message: string;",
        "  code: number;",
        "  errors?: Record<string, string[]>;",
        "}",
        "",
        "/** User type example */",
        "export interface User {",
        "  id: string;",
        "  email: string;",
        "  name: string;",
        "  avatar?: string;",
        "  createdAt: string;",
        "  updatedAt: string;",
        "}",
        "",
        "/** Auth response */",
        "export interface AuthResponse {",
        "  user: User;",
        "  token: string;",
        "  refreshToken: string;",
        "}"
      ),
    },
    {
      path: "api/queries.ts",
      content: lines(
        'import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";',
        'import { apiClient, handleApiError } from "./client";',
        'import type { ApiResponse } from "./types";',
        "",
        "/**",
        " * Example query hook for fetching data.",
        " */",
        "export function useApiQuery<T>(",
        "  key: string[],",
        "  url: string,",
        "  params?: Record<string, string>",
        ") {",
        "  return useQuery({",
        "    queryKey: key,",
        "    queryFn: () => apiClient.get<T>(url, params),",
        "    retry: 2,",
        "    staleTime: 5 * 60 * 1000,",
        "  });",
        "}",
        "",
        "/**",
        " * Example mutation hook for posting data.",
        " */",
        "export function useApiMutation<TData, TVariables>(",
        "  url: string,",
        '  method: "POST" | "PUT" | "PATCH" = "POST"',
        ") {",
        "  const queryClient = useQueryClient();",
        "",
        "  return useMutation({",
        "    mutationFn: (variables: TVariables) => {",
        "      switch (method) {",
        '        case "PUT":',
        "          return apiClient.put<TData>(url, variables);",
        '        case "PATCH":',
        "          return apiClient.patch<TData>(url, variables);",
        "        default:",
        "          return apiClient.post<TData>(url, variables);",
        "      }",
        "    },",
        "    onSuccess: () => {",
        "      queryClient.invalidateQueries({ queryKey: [url] });",
        "    },",
        "    onError: (error) => {",
        "      handleApiError(error);",
        "    },",
        "  });",
        "}",
        "",
        "/**",
        " * Example: Fetch current user profile",
        " */",
        "export function useUserProfile() {",
        "  return useApiQuery<ApiResponse<{ name: string; email: string }>>(",
        '    ["user", "profile"],',
        '    "/user/profile"',
        "  );",
        "}"
      ),
    },
  ],
  layoutProviders: ["<QueryClientProvider client={queryClient}>"],
  layoutImports: [
    'import { QueryClient, QueryClientProvider } from "@tanstack/react-query";',
    "const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 2, staleTime: 5 * 60 * 1000 } } });",
  ],
};

export default networkModule;
