import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const notificationModule: ModuleDef = {
  id: "notification",
  name: "应用内通知",
  description: "expo-notifications + 自定义组件",
  defaultChecked: false,
  dependencies: {
    "expo-notifications": "~0.32.17",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/notification/index.ts",
      content: lines(
        'export { InAppNotification, useInAppNotification } from "./InAppNotification";',
        'export { setupNotificationHandlers } from "./InAppNotification";'
      ),
    },
    {
      path: "src/modules/notification/InAppNotification.tsx",
      content: lines(
        'import React, {',
        "  createContext,",
        "  useCallback,",
        "  useContext,",
        "  useEffect,",
        "  useMemo,",
        "  useRef,",
        "  useState,",
        '} from "react";',
        'import { Animated, StyleSheet, Text, TouchableOpacity, View } from "react-native";',
        'import * as Notifications from "expo-notifications";',
        'import type { Subscription } from "expo-notifications";',
        "",
        "export function setupNotificationHandlers(): void {",
        "  Notifications.setNotificationHandler({",
        "    handleNotification: async () => ({",
        "      shouldShowAlert: true,",
        "      shouldPlaySound: true,",
        "      shouldSetBadge: true,",
        "    }),",
        "  });",
        "}",
        "",
        "interface NotificationData {",
        "  id: string;",
        "  title: string;",
        "  message: string;",
        '  type: "info" | "success" | "warning" | "error";',
        "  duration?: number;",
        "}",
        "",
        "interface InAppNotificationContextType {",
        "  showNotification: (data: Omit<NotificationData, \"id\">) => void;",
        "}",
        "",
        "const InAppNotificationContext = createContext<InAppNotificationContextType>({",
        "  showNotification: () => {},",
        "});",
        "",
        "export function useInAppNotification(): InAppNotificationContextType {",
        "  return useContext(InAppNotificationContext);",
        "}",
        "",
        "let notificationIdCounter = 0;",
        "",
        "export function InAppNotificationProvider({",
        "  children,",
        "}: {",
        "  children: React.ReactNode;",
        "}) {",
        "  const [notifications, setNotifications] = useState<NotificationData[]>([]);",
        "  const timersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(new Map());",
        "",
        "  const removeNotification = useCallback((id: string) => {",
        "    setNotifications((prev) => prev.filter((n) => n.id !== id));",
        "    const timer = timersRef.current.get(id);",
        "    if (timer) {",
        "      clearTimeout(timer);",
        "      timersRef.current.delete(id);",
        "    }",
        "  }, []);",
        "",
        "  const showNotification = useCallback(",
        "    (data: Omit<NotificationData, \"id\">) => {",
        '      const id = `notification-${++notificationIdCounter}`;',
        "      const notification: NotificationData = { ...data, id };",
        "      setNotifications((prev) => [...prev, notification]);",
        "",
        "      const duration = data.duration ?? 3000;",
        "      const timer = setTimeout(() => {",
        "        removeNotification(id);",
        "      }, duration);",
        "      timersRef.current.set(id, timer);",
        "    },",
        "    [removeNotification]",
        "  );",
        "",
        "  const contextValue = useMemo(",
        "    () => ({ showNotification }),",
        "    [showNotification]",
        "  );",
        "",
        "  return (",
        "    <InAppNotificationContext.Provider value={contextValue}>",
        "      {children}",
        '      <View style={styles.container} pointerEvents="box-none">',
        "        {notifications.map((notification) => (",
        "          <NotificationCard",
        "            key={notification.id}",
        "            notification={notification}",
        "            onDismiss={() => removeNotification(notification.id)}",
        "          />",
        "        ))}",
        "      </View>",
        "    </InAppNotificationContext.Provider>",
        "  );",
        "}",
        "",
        "interface NotificationCardProps {",
        "  notification: NotificationData;",
        "  onDismiss: () => void;",
        "}",
        "",
        "const typeColors: Record<NotificationData[\"type\"], string> = {",
        '  info: "#007AFF",',
        '  success: "#34C759",',
        '  warning: "#FF9500",',
        '  error: "#FF3B30",',
        "};",
        "",
        "function NotificationCard({ notification, onDismiss }: NotificationCardProps) {",
        "  const opacity = useRef(new Animated.Value(0)).current;",
        "",
        "  useEffect(() => {",
        "    Animated.timing(opacity, {",
        "      toValue: 1,",
        "      duration: 300,",
        "      useNativeDriver: true,",
        "    }).start();",
        "  }, [opacity]);",
        "",
        "  const handleDismiss = useCallback(() => {",
        "    Animated.timing(opacity, {",
        "      toValue: 0,",
        "      duration: 200,",
        "      useNativeDriver: true,",
        "    }).start(() => onDismiss());",
        "  }, [opacity, onDismiss]);",
        "",
        "  return (",
        '    <Animated.View style={[styles.card, { opacity }]}>',
        "      <View",
        "        style={[styles.accent, { backgroundColor: typeColors[notification.type] }]}",
        "      />",
        "      <View style={styles.content}>",
        "        <Text style={styles.title}>{notification.title}</Text>",
        "        <Text style={styles.message}>{notification.message}</Text>",
        "      </View>",
        "      <TouchableOpacity onPress={handleDismiss} style={styles.closeButton}>",
        '        <Text style={styles.closeButtonText}>X</Text>',
        "      </TouchableOpacity>",
        "    </Animated.View>",
        "  );",
        "}",
        "",
        "const styles = StyleSheet.create({",
        "  container: {",
        "    position: \"absolute\",",
        "    top: 60,",
        "    left: 16,",
        "    right: 16,",
        "    zIndex: 9999,",
        "    gap: 8,",
        "  },",
        "  card: {",
        "    flexDirection: \"row\",",
        '    alignItems: "center",',
        '    backgroundColor: "#fff",',
        "    borderRadius: 12,",
        '    shadowColor: "#000",',
        "    shadowOffset: { width: 0, height: 2 },",
        "    shadowOpacity: 0.15,",
        "    shadowRadius: 8,",
        "    elevation: 5,",
        '    overflow: "hidden",',
        "  },",
        "  accent: {",
        "    width: 4,",
        '    height: "100%",',
        "    minHeight: 48,",
        "  },",
        "  content: {",
        "    flex: 1,",
        "    paddingVertical: 12,",
        "    paddingHorizontal: 12,",
        "  },",
        "  title: {",
        "    fontSize: 14,",
        '    fontWeight: "600",',
        '    color: "#1a1a1a",',
        "  },",
        "  message: {",
        "    fontSize: 13,",
        '    color: "#666",',
        "    marginTop: 2,",
        "  },",
        "  closeButton: {",
        "    padding: 12,",
        "  },",
        "  closeButtonText: {",
        "    fontSize: 14,",
        '    color: "#999",',
        "  },",
        "});",
        "",
        "export const InAppNotification = InAppNotificationProvider;"
      ),
    },
  ],
  layoutProviders: ["<InAppNotification>"],
  layoutImports: [
    'import { InAppNotification } from "../modules/notification/InAppNotification";',
  ],
};

export default notificationModule;
