import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const otaModule: ModuleDef = {
  id: "ota",
  name: "OTA 更新",
  description: "expo-updates",
  defaultChecked: false,
  dependencies: {
    "expo-updates": "~7.0.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/ota/useOTAUpdate.ts",
      content: lines(
        'import { useCallback, useEffect, useState } from "react";',
        'import * as Updates from "expo-updates";',
        'import { Alert, Platform } from "react-native";',
        "",
        "interface OTAUpdateState {",
        "  isUpdateAvailable: boolean;",
        "  isDownloading: boolean;",
        "  progress: number;",
        "  error: string | null;",
        "}",
        "",
        "export function useOTAUpdate() {",
        "  const [state, setState] = useState<OTAUpdateState>({",
        "    isUpdateAvailable: false,",
        "    isDownloading: false,",
        "    progress: 0,",
        "    error: null,",
        "  });",
        "",
        "  const checkForUpdate = useCallback(async () => {",
        "    if (__DEV__ || Platform.OS === \"web\") {",
        "      return;",
        "    }",
        "",
        "    try {",
        "      const update = await Updates.checkForUpdateAsync();",
        "      setState((prev) => ({",
        "        ...prev,",
        "        isUpdateAvailable: update.isAvailable,",
        "        error: null,",
        "      }));",
        "      return update.isAvailable;",
        "    } catch (error) {",
        "      const message = error instanceof Error ? error.message : \"检查更新失败\";",
        "      setState((prev) => ({ ...prev, error: message }));",
        "      return false;",
        "    }",
        "  }, []);",
        "",
        "  const downloadUpdate = useCallback(async () => {",
        "    if (__DEV__ || Platform.OS === \"web\") return null;",
        "",
        "    try {",
        "      setState((prev) => ({ ...prev, isDownloading: true, progress: 0 }));",
        "      const result = await Updates.fetchUpdateAsync();",
        "      setState((prev) => ({",
        "        ...prev,",
        "        isDownloading: false,",
        "        isUpdateAvailable: false,",
        "        progress: 1,",
        "      }));",
        "      return result;",
        "    } catch (error) {",
        "      const message = error instanceof Error ? error.message : \"下载更新失败\";",
        "      setState((prev) => ({",
        "        ...prev,",
        "        isDownloading: false,",
        "        error: message,",
        "      }));",
        "      return null;",
        "    }",
        "  }, []);",
        "",
        "  const downloadAndRestart = useCallback(async () => {",
        "    const result = await downloadUpdate();",
        "    if (result?.isNew) {",
        "      Alert.alert(",
        '        "更新已下载",',
        '        "应用需要重启以完成更新，是否立即重启？",',
        "        [",
        '          { text: "稍后", style: "cancel" },',
        "          {",
        '            text: "立即重启",',
        '            style: "default",',
        "            onPress: async () => {",
        "              await Updates.reloadAsync();",
        "            },",
        "          },",
        "        ]",
        "      );",
        "    }",
        "  }, [downloadUpdate]);",
        "",
        "  const restartApp = useCallback(async () => {",
        "    await Updates.reloadAsync();",
        "  }, []);",
        "",
        "  useEffect(() => {",
        "    checkForUpdate();",
        "  }, [checkForUpdate]);",
        "",
        "  return {",
        "    ...state,",
        "    checkForUpdate,",
        "    downloadUpdate,",
        "    downloadAndRestart,",
        "    restartApp,",
        "  };",
        "}"
      ),
    },
  ],
};

export default otaModule;
