import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const paymentModule: ModuleDef = {
  id: "payment",
  name: "Apple/iOS 支付",
  description: "react-native-iap 封装",
  defaultChecked: false,
  dependencies: {
    "react-native-iap": "^12.15.0",
  },
  devDependencies: {},
  files: [
    {
      path: "modules/payment/index.ts",
      content: lines(
        'export { usePayment } from "./usePayment";',
        'export type { ProductInfo, PurchaseResult, PaymentError } from "./types";'
      ),
    },
    {
      path: "modules/payment/types.ts",
      content: lines(
        'import type { Product, Purchase } from "react-native-iap";',
        "",
        "export interface ProductInfo {",
        "  productId: string;",
        "  title: string;",
        "  description: string;",
        "  price: string;",
        "  currency: string;",
        "}",
        "",
        "export interface PurchaseResult {",
        "  success: boolean;",
        "  purchase?: Purchase;",
        "  error?: PaymentError;",
        "}",
        "",
        "export interface PaymentError {",
        "  code: string;",
        "  message: string;",
        "  nativeError?: unknown;",
        "}",
        "",
        "export interface PaymentConfig {",
        "  productIds: string[];",
        "  subscriptionIds?: string[];",
        "}"
      ),
    },
    {
      path: "modules/payment/usePayment.ts",
      content: lines(
        'import { useCallback, useEffect, useRef, useState } from "react";',
        'import {',
        "  initConnection,",
        "  endConnection,",
        "  getProducts,",
        "  requestPurchase,",
        "  requestSubscription,",
        "  finishTransaction,",
        "  purchaseUpdatedListener,",
        "  purchaseErrorListener,",
        "  Product,",
        "  Purchase,",
        "  PurchaseError,",
        '} from "react-native-iap";',
        'import type { PaymentConfig, ProductInfo, PurchaseResult, PaymentError as AppPaymentError } from "./types";',
        "",
        "export function usePayment(config: PaymentConfig) {",
        "  const [products, setProducts] = useState<ProductInfo[]>([]);",
        "  const [isLoading, setIsLoading] = useState(false);",
        "  const [isConnected, setIsConnected] = useState(false);",
        "  const purchaseUpdateSubscription = useRef<ReturnType<typeof purchaseUpdatedListener> | null>(null);",
        "  const purchaseErrorSubscription = useRef<ReturnType<typeof purchaseErrorListener> | null>(null);",
        "",
        "  const initialize = useCallback(async () => {",
        "    try {",
        "      setIsLoading(true);",
        "      const connected = await initConnection();",
        "      setIsConnected(connected);",
        "",
        "      if (connected) {",
        "        const allIds = [...config.productIds, ...(config.subscriptionIds || [])];",
        "        if (allIds.length > 0) {",
        '          const fetchedProducts = await getProducts({ skus: allIds });',
        "          const mapped = fetchedProducts.map(mapProductToInfo);",
        "          setProducts(mapped);",
        "        }",
        "      }",
        "    } catch (error) {",
        '      console.error("[Payment] Initialization failed:", error);',
        "    } finally {",
        "      setIsLoading(false);",
        "    }",
        "  }, [config.productIds, config.subscriptionIds]);",
        "",
        "  const handlePurchase = useCallback(",
        "    async (purchase: Purchase): Promise<void> => {",
        "      const receipt = purchase.transactionReceipt;",
        "      if (receipt) {",
        "        // TODO: Validate receipt with your backend server",
        "        await finishTransaction({ purchase, isConsumable: false });",
        "      }",
        "    },",
        "    []",
        "  );",
        "",
        "  const buyProduct = useCallback(",
        "    async (productId: string): Promise<PurchaseResult> => {",
        "      try {",
        '        const purchase = await requestPurchase({ sku: productId });',
        "        if (purchase && purchase.length > 0) {",
        "          await handlePurchase(purchase[0]);",
        "          return { success: true, purchase: purchase[0] };",
        "        }",
        "        return { success: false };",
        "      } catch (error) {",
        "        const paymentError = mapError(error);",
        "        return { success: false, error: paymentError };",
        "      }",
        "    },",
        "    [handlePurchase]",
        "  );",
        "",
        "  const buySubscription = useCallback(",
        "    async (subscriptionId: string): Promise<PurchaseResult> => {",
        "      try {",
        '        const purchase = await requestSubscription({ sku: subscriptionId });',
        "        if (purchase && purchase.length > 0) {",
        "          await handlePurchase(purchase[0]);",
        "          return { success: true, purchase: purchase[0] };",
        "        }",
        "        return { success: false };",
        "      } catch (error) {",
        "        const paymentError = mapError(error);",
        "        return { success: false, error: paymentError };",
        "      }",
        "    },",
        "    [handlePurchase]",
        "  );",
        "",
        "  useEffect(() => {",
        "    initialize();",
        "",
        "    purchaseUpdateSubscription.current = purchaseUpdatedListener(",
        "      async (purchase: Purchase) => {",
        '        console.log("[Payment] Purchase updated:", purchase.transactionId);',
        "        await handlePurchase(purchase);",
        "      }",
        "    );",
        "",
        "    purchaseErrorSubscription.current = purchaseErrorListener(",
        "      (error: PurchaseError) => {",
        '        console.error("[Payment] Purchase error:", error.message);',
        "      }",
        "    );",
        "",
        "    return () => {",
        "      purchaseUpdateSubscription.current?.remove();",
        "      purchaseErrorSubscription.current?.remove();",
        "      endConnection();",
        "    };",
        "  }, [initialize, handlePurchase]);",
        "",
        "  return {",
        "    products,",
        "    isLoading,",
        "    isConnected,",
        "    buyProduct,",
        "    buySubscription,",
        "    refresh: initialize,",
        "  };",
        "}",
        "",
        "function mapProductToInfo(product: Product): ProductInfo {",
        "  return {",
        "    productId: product.productId,",
        "    title: product.title,",
        "    description: product.description,",
        "    price: product.price,",
        '    currency: product.currency || "USD",',
        "  };",
        "}",
        "",
        "function mapError(error: unknown): AppPaymentError {",
        "  if (error instanceof Error) {",
        "    return {",
        '      code: "PURCHASE_ERROR",',
        "      message: error.message,",
        "    };",
        "  }",
        "  return {",
        '    code: "UNKNOWN_ERROR",',
        '    message: "An unknown error occurred",',
        "  };",
        "}"
      ),
    },
  ],
};

export default paymentModule;
