import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const permissionModule: ModuleDef = {
  id: "permission",
  name: "用户权限管理",
  description: "权限请求/检查封装",
  defaultChecked: false,
  dependencies: {
    "expo-image-picker": "~17.0.11",
    "expo-camera": "~17.0.10",
    "expo-location": "~19.0.8",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/permission/index.ts",
      content: lines(
        'import * as ImagePicker from "expo-image-picker";',
        'import * as Camera from "expo-camera";',
        'import * as Location from "expo-location";',
        'import { Alert, Platform } from "react-native";',
        "",
        'export type PermissionStatus = "granted" | "denied" | "undetermined";',
        "",
        "export interface PermissionResult {",
        "  status: PermissionStatus;",
        "  canAskAgain: boolean;",
        "}",
        "",
        "export async function checkCameraPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } = await Camera.getCameraPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function requestCameraPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } = await Camera.requestCameraPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function checkPhotoLibraryPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } =",
        "    await ImagePicker.getMediaLibraryPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function requestPhotoLibraryPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } =",
        "    await ImagePicker.requestMediaLibraryPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function checkLocationPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } = await Location.getForegroundPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function requestLocationPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } =",
        "    await Location.requestForegroundPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function requestBackgroundLocationPermission(): Promise<PermissionResult> {",
        "  const { status, canAskAgain } =",
        "    await Location.requestBackgroundPermissionsAsync();",
        "  return { status: status as PermissionStatus, canAskAgain };",
        "}",
        "",
        "export async function requestPermissionWithAlert(",
        "  permissionName: string,",
        "  requestFn: () => Promise<PermissionResult>,",
        "  onGranted?: () => void,",
        "  onDenied?: () => void",
        "): Promise<PermissionResult> {",
        "  const result = await requestFn();",
        "",
        '  if (result.status === "granted") {',
        "    onGranted?.();",
        "  } else {",
        "    const message = result.canAskAgain",
        '      ? `您需要授予${permissionName}权限才能使用此功能`',
        '      : `${permissionName}权限已被拒绝，请在系统设置中手动开启`;',
        "",
        '    Alert.alert("需要权限", message, [',
        '      { text: "取消", style: "cancel", onPress: onDenied },',
        "      ...(result.canAskAgain",
        "        ? [",
        "            {",
        '              text: "再次请求",',
        '              style: "default" as const,',
        "              onPress: () => requestFn(),",
        "            },",
        "          ]",
        "        : []),",
        "    ]);",
        "  }",
        "",
        "  return result;",
        "}",
        "",
        "export async function pickImageWithPermission(): Promise<ImagePicker.ImagePickerResult | null> {",
        "  const permission = await requestPhotoLibraryPermission();",
        '  if (permission.status !== "granted") {',
        '    Alert.alert("需要权限", "请授予相册访问权限");',
        "    return null;",
        "  }",
        "",
        "  const result = await ImagePicker.launchImageLibraryAsync({",
        "    mediaTypes: ImagePicker.MediaTypeOptions.Images,",
        "    allowsEditing: true,",
        "    aspect: [1, 1],",
        "    quality: 0.8,",
        "  });",
        "",
        "  return result;",
        "}",
        "",
        "export async function takePhotoWithPermission(): Promise<ImagePicker.ImagePickerResult | null> {",
        "  const permission = await requestCameraPermission();",
        '  if (permission.status !== "granted") {',
        '    Alert.alert("需要权限", "请授予相机访问权限");',
        "    return null;",
        "  }",
        "",
        "  const result = await ImagePicker.launchCameraAsync({",
        "    allowsEditing: true,",
        "    aspect: [1, 1],",
        "    quality: 0.8,",
        "  });",
        "",
        "  return result;",
        "}"
      ),
    },
  ],
  appConfig: {
    plugins: [
      [
        "expo-camera",
        {
          cameraPermission: "Allow $(PRODUCT_NAME) to access your camera",
        },
      ],
      [
        "expo-image-picker",
        {
          photosPermission: "Allow $(PRODUCT_NAME) to access your photos",
        },
      ],
      [
        "expo-location",
        {
          locationAlwaysAndWhenInUsePermission:
            "Allow $(PRODUCT_NAME) to use your location",
        },
      ],
    ],
  },
};

export default permissionModule;
