import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const stateModule: ModuleDef = {
  id: "state",
  name: "状态管理",
  description: "Zustand stores 模板，persist 中间件",
  defaultChecked: true,
  dependencies: {
    zustand: "^5.0.0",
  },
  devDependencies: {},
  files: [
    {
      path: "stores/index.ts",
      content: lines('export { useUserStore } from "./slices/userSlice";'),
    },
    {
      path: "stores/slices/userSlice.ts",
      content: lines(
        'import { create } from "zustand";',
        'import { persist, createJSONStorage } from "zustand/middleware";',
        "",
        "interface User {",
        "  id: string;",
        "  email: string;",
        "  name: string;",
        "  avatar?: string;",
        "}",
        "",
        "interface UserState {",
        "  user: User | null;",
        "  token: string | null;",
        "  isAuthenticated: boolean;",
        "  hasHydrated: boolean;",
        "",
        "  setUser: (user: User, token: string) => void;",
        "  updateUser: (partial: Partial<User>) => void;",
        "  clearUser: () => void;",
        "  setHasHydrated: (value: boolean) => void;",
        "}",
        "",
        "export const useUserStore = create<UserState>()(",
        "  persist(",
        "    (set, get) => ({",
        "      user: null,",
        "      token: null,",
        "      isAuthenticated: false,",
        "      hasHydrated: false,",
        "",
        "      setUser: (user: User, token: string) => {",
        "        set({ user, token, isAuthenticated: true });",
        "      },",
        "",
        "      updateUser: (partial: Partial<User>) => {",
        "        const currentUser = get().user;",
        "        if (currentUser) {",
        "          set({ user: { ...currentUser, ...partial } });",
        "        }",
        "      },",
        "",
        "      clearUser: () => {",
        "        set({ user: null, token: null, isAuthenticated: false });",
        "      },",
        "",
        "      setHasHydrated: (value: boolean) => {",
        "        set({ hasHydrated: value });",
        "      },",
        "    }),",
        "    {",
        '      name: "user-store",',
        "      storage: createJSONStorage(() => {",
        "        try {",
        '          const { MMKV } = require("react-native-mmkv");',
        "          const storage = new MMKV();",
        "          return {",
        "            getItem: (name: string) => {",
        "              const value = storage.getString(name);",
        "              return value ?? null;",
        "            },",
        "            setItem: (name: string, value: string) => {",
        "              storage.set(name, value);",
        "            },",
        "            removeItem: (name: string) => {",
        "              storage.delete(name);",
        "            },",
        "          };",
        "        } catch {",
        "          return {",
        "            getItem: () => null,",
        "            setItem: () => {},",
        "            removeItem: () => {},",
        "          };",
        "        }",
        "      }),",
        "      partialize: (state) => ({",
        "        user: state.user,",
        "        token: state.token,",
        "        isAuthenticated: state.isAuthenticated,",
        "      }),",
        "      onRehydrateStorage: () => (state) => {",
        "        state?.setHasHydrated(true);",
        "      },",
        "    }",
        "  )",
        ");"
      ),
    },
  ],
};

export default stateModule;
