import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const storageModule: ModuleDef = {
  id: "storage",
  name: "本地存储",
  description: "MMKV 封装，类型安全 API",
  defaultChecked: true,
  dependencies: {
    "react-native-mmkv": "^3.1.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/storage/index.ts",
      content: lines(
        'import { MMKV } from "react-native-mmkv";',
        "",
        "/**",
        " * Centralized MMKV storage instance.",
        " */",
        "const storage = new MMKV({",
        '  id: "app-storage",',
        "  encryptionKey: process.env.EXPO_PUBLIC_STORAGE_KEY || undefined,",
        "});",
        "",
        "/** Storage keys */",
        "export const StorageKeys = {",
        '  AUTH_TOKEN: "auth_token",',
        '  REFRESH_TOKEN: "refresh_token",',
        '  USER_DATA: "user_data",',
        '  THEME: "theme",',
        '  LANGUAGE: "language",',
        '  ONBOARDING_COMPLETED: "onboarding_completed",',
        '  LAST_SYNC_TIME: "last_sync_time",',
        '  CACHE_VERSION: "cache_version",',
        "} as const;",
        "",
        "export type StorageKey = (typeof StorageKeys)[keyof typeof StorageKeys];",
        "",
        "export function getString(key: StorageKey): string | null {",
        "  return storage.getString(key) ?? null;",
        "}",
        "",
        "export function setString(key: StorageKey, value: string): void {",
        "  storage.set(key, value);",
        "}",
        "",
        "export function getNumber(key: StorageKey): number | null {",
        "  const value = storage.getNumber(key);",
        "  return value ?? null;",
        "}",
        "",
        "export function setNumber(key: StorageKey, value: number): void {",
        "  storage.set(key, value);",
        "}",
        "",
        "export function getBoolean(key: StorageKey): boolean | null {",
        "  const value = storage.getBoolean(key);",
        "  return value ?? null;",
        "}",
        "",
        "export function setBoolean(key: StorageKey, value: boolean): void {",
        "  storage.set(key, value);",
        "}",
        "",
        "export function getJson<T>(key: StorageKey): T | null {",
        "  const raw = storage.getString(key);",
        "  if (raw === undefined) return null;",
        "  try {",
        "    return JSON.parse(raw) as T;",
        "  } catch {",
        "    return null;",
        "  }",
        "}",
        "",
        "export function setJson<T>(key: StorageKey, value: T): void {",
        "  storage.set(key, JSON.stringify(value));",
        "}",
        "",
        "export function remove(key: StorageKey): void {",
        "  storage.delete(key);",
        "}",
        "",
        "export function contains(key: StorageKey): boolean {",
        "  return storage.contains(key);",
        "}",
        "",
        "export function clearAll(): void {",
        "  storage.clearAll();",
        "}",
        "",
        "export function getAllKeys(): string[] {",
        "  return storage.getAllKeys();",
        "}",
        "",
        "export default storage;"
      ),
    },
  ],
  appConfig: {
    plugins: [
      [
        "react-native-mmkv",
        {
          MMKV_APP_ID: "app-storage",
        },
      ],
    ],
  },
};

export default storageModule;
