import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const uiReusablesModule: ModuleDef = {
  id: "ui-reusables",
  name: "reactnative.reusables UI",
  description: "预置 UI 组件 (Button, AlertDialog, Card, Input, Label, Text, Separator)",
  defaultChecked: false,
  dependencies: {
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.6.0",
    "@rn-primitives/slot": "^1.1.0",
    "@rn-primitives/types": "^1.1.0",
    "@rn-primitives/label": "^1.1.0",
    "@rn-primitives/separator": "^1.1.0",
    "@rn-primitives/alert-dialog": "^1.1.0",
    "react-native-svg": "^15.8.0",
  },
  devDependencies: {},
  files: [
    // ─── lib/utils.ts ────────────────────────────────────────────────────
    {
      path: "src/lib/utils.ts",
      content: lines(
        'import { type ClassValue, clsx } from "clsx";',
        'import { twMerge } from "tailwind-merge";',
        "",
        "export function cn(...inputs: ClassValue[]) {",
        "  return twMerge(clsx(inputs));",
        "}",
        ""
      ),
    },

    // ─── components/ui/text.tsx ──────────────────────────────────────────
    {
      path: "src/components/ui/text.tsx",
      content: lines(
        'import { cn } from "@/src/lib/utils";',
        'import { Slot } from "@rn-primitives/slot";',
        'import { cva, type VariantProps } from "class-variance-authority";',
        'import * as React from "react";',
        'import { Platform, Text as RNText, type Role } from "react-native";',
        "",
        "const textVariants = cva(",
        "  cn(",
        '    "text-foreground text-base",',
        "    Platform.select({",
        '      web: "select-text",',
        "    })",
        "  ),",
        "  {",
        "    variants: {",
        "      variant: {",
        "        default: \"\",",
        "        h1: cn(",
        '          "text-center text-4xl font-extrabold tracking-tight",',
        "          Platform.select({ web: \"scroll-m-20 text-balance\" })",
        "        ),",
        "        h2: cn(",
        '          "border-border border-b pb-2 text-3xl font-semibold tracking-tight",',
        '          Platform.select({ web: "scroll-m-20 first:mt-0" })',
        "        ),",
        "        h3: cn(",
        '          "text-2xl font-semibold tracking-tight",',
        '          Platform.select({ web: "scroll-m-20" })',
        "        ),",
        "        h4: cn(",
        '          "text-xl font-semibold tracking-tight",',
        '          Platform.select({ web: "scroll-m-20" })',
        "        ),",
        '        p: "mt-3 leading-7 sm:mt-6",',
        '        blockquote: "mt-4 border-l-2 pl-3 italic sm:mt-6 sm:pl-6",',
        "        code: cn(",
        '          "bg-muted relative rounded px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold"',
        "        ),",
        '        lead: "text-muted-foreground text-xl",',
        '        large: "text-lg font-semibold",',
        '        small: "text-sm font-medium leading-none",',
        '        muted: "text-muted-foreground text-sm",',
        "      },",
        "    },",
        "    defaultVariants: {",
        "      variant: \"default\",",
        "    },",
        "  }",
        ");",
        "",
        "type TextVariantProps = VariantProps<typeof textVariants>;",
        "",
        "type TextVariant = NonNullable<TextVariantProps[\"variant\"]>;",
        "",
        "const ROLE: Partial<Record<TextVariant, Role>> = {",
        '  h1: "heading",',
        '  h2: "heading",',
        '  h3: "heading",',
        '  h4: "heading",',
        "  blockquote: Platform.select({ web: \"blockquote\" as Role }),",
        "  code: Platform.select({ web: \"code\" as Role }),",
        "};",
        "",
        "const ARIA_LEVEL: Partial<Record<TextVariant, string>> = {",
        '  h1: "1",',
        '  h2: "2",',
        '  h3: "3",',
        '  h4: "4",',
        "};",
        "",
        "const TextClassContext = React.createContext<string | undefined>(undefined);",
        "",
        "function Text({",
        "  className,",
        "  asChild = false,",
        '  variant = "default",',
        "  ...props",
        "}: React.ComponentProps<typeof RNText> &",
        "  React.RefAttributes<typeof RNText> &",
        "  TextVariantProps & { asChild?: boolean }) {",
        "  const textClass = React.useContext(TextClassContext);",
        "  const Component = asChild ? Slot : RNText;",
        "  return (",
        "    <Component",
        "      className={cn(textVariants({ variant }), textClass, className)}",
        "      role={variant ? ROLE[variant] : undefined}",
        "      aria-level={variant ? ARIA_LEVEL[variant] : undefined}",
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "export { Text, TextClassContext };",
        ""
      ),
    },

    // ─── components/ui/button.tsx ────────────────────────────────────────
    {
      path: "src/components/ui/button.tsx",
      content: lines(
        'import { TextClassContext } from "@/src/components/ui/text";',
        'import { cn } from "@/src/lib/utils";',
        'import { cva, type VariantProps } from "class-variance-authority";',
        'import { Platform, Pressable } from "react-native";',
        "",
        "const buttonVariants = cva(",
        "  cn(",
        '    "group shrink-0 flex-row items-center justify-center gap-2 rounded-md shadow-none",',
        "    Platform.select({",
        '      web: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive whitespace-nowrap outline-none transition-all focus-visible:ring-[3px] disabled:pointer-events-none [&_svg:not([class*=\'size-\'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",',
        "    })",
        "  ),",
        "  {",
        "    variants: {",
        "      variant: {",
        "        default: cn(",
        '          "bg-primary active:bg-primary/90 shadow-sm shadow-black/5",',
        '          Platform.select({ web: "hover:bg-primary/90" })',
        "        ),",
        "        destructive: cn(",
        '          "bg-destructive active:bg-destructive/90 dark:bg-destructive/60 shadow-sm shadow-black/5",',
        "          Platform.select({",
        '            web: "hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40",',
        "          })",
        "        ),",
        "        outline: cn(",
        '          "border-border bg-background active:bg-accent dark:bg-input/30 dark:border-input dark:active:bg-input/50 border shadow-sm shadow-black/5",',
        "          Platform.select({",
        '            web: "hover:bg-accent dark:hover:bg-input/50",',
        "          })",
        "        ),",
        "        secondary: cn(",
        '          "bg-secondary active:bg-secondary/80 shadow-sm shadow-black/5",',
        '          Platform.select({ web: "hover:bg-secondary/80" })',
        "        ),",
        "        ghost: cn(",
        '          "active:bg-accent dark:active:bg-accent/50",',
        '          Platform.select({ web: "hover:bg-accent dark:hover:bg-accent/50" })',
        "        ),",
        '        link: "",',
        "      },",
        "      size: {",
        "        default: cn(",
        '          "h-10 px-4 py-2 sm:h-9",',
        '          Platform.select({ web: "has-[>svg]:px-3" })',
        "        ),",
        "        sm: cn(",
        '          "h-9 gap-1.5 rounded-md px-3 sm:h-8",',
        '          Platform.select({ web: "has-[>svg]:px-2.5" })',
        "        ),",
        "        lg: cn(",
        '          "h-11 rounded-md px-6 sm:h-10",',
        '          Platform.select({ web: "has-[>svg]:px-4" })',
        "        ),",
        '        icon: "h-10 w-10 sm:h-9 sm:w-9",',
        "      },",
        "    },",
        "    defaultVariants: {",
        '      variant: "default",',
        '      size: "default",',
        "    },",
        "  }",
        ");",
        "",
        "const buttonTextVariants = cva(",
        "  cn(",
        '    "text-foreground text-sm font-medium",',
        '    Platform.select({ web: "pointer-events-none transition-colors" })',
        "  ),",
        "  {",
        "    variants: {",
        "      variant: {",
        '        default: "text-primary-foreground",',
        '        destructive: "text-white",',
        "        outline: cn(",
        '          "group-active:text-accent-foreground",',
        '          Platform.select({ web: "group-hover:text-accent-foreground" })',
        "        ),",
        '        secondary: "text-secondary-foreground",',
        '        ghost: "group-active:text-accent-foreground",',
        "        link: cn(",
        '          "text-primary group-active:underline",',
        '          Platform.select({ web: "underline-offset-4 hover:underline group-hover:underline" })',
        "        ),",
        "      },",
        "      size: {",
        '        default: "",',
        '        sm: "",',
        '        lg: "",',
        '        icon: "",',
        "      },",
        "    },",
        "    defaultVariants: {",
        '      variant: "default",',
        '      size: "default",',
        "    },",
        "  }",
        ");",
        "",
        "type ButtonProps = React.ComponentProps<typeof Pressable> &",
        "  React.RefAttributes<typeof Pressable> &",
        "  VariantProps<typeof buttonVariants>;",
        "",
        "function Button({ className, variant, size, ...props }: ButtonProps) {",
        "  return (",
        "    <TextClassContext.Provider value={buttonTextVariants({ variant, size })}>",
        "      <Pressable",
        '        className={cn(props.disabled && "opacity-50", buttonVariants({ variant, size }), className)}',
        '        role="button"',
        "        {...props}",
        "      />",
        "    </TextClassContext.Provider>",
        "  );",
        "}",
        "",
        "export { Button, buttonTextVariants, buttonVariants };",
        "export type { ButtonProps };",
        ""
      ),
    },

    // ─── components/ui/input.tsx ──────────────────────────────────────────
    {
      path: "src/components/ui/input.tsx",
      content: lines(
        'import { cn } from "@/src/lib/utils";',
        'import { Platform, TextInput } from "react-native";',
        "",
        "function Input({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof TextInput> & React.RefAttributes<TextInput>) {",
        "  return (",
        "    <TextInput",
        "      className={cn(",
        '        "dark:bg-input/30 border-input bg-background text-foreground flex h-10 w-full min-w-0 flex-row items-center rounded-md border px-3 py-1 text-base leading-5 shadow-sm shadow-black/5 sm:h-9",',
        "        props.editable === false &&",
        "          cn(",
        '            "opacity-50",',
        '            Platform.select({ web: "disabled:pointer-events-none disabled:cursor-not-allowed" })',
        "          ),",
        "        Platform.select({",
        "          web: cn(",
        '            "placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground outline-none transition-[color,box-shadow] md:text-sm",',
        '            "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",',
        '            "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive"',
        "          ),",
        '          native: "placeholder:text-muted-foreground/50",',
        "        }),",
        "        className",
        "      )}",
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "export { Input };",
        ""
      ),
    },

    // ─── components/ui/label.tsx ─────────────────────────────────────────
    {
      path: "src/components/ui/label.tsx",
      content: lines(
        'import { cn } from "@/src/lib/utils";',
        'import * as LabelPrimitive from "@rn-primitives/label";',
        'import { Platform } from "react-native";',
        "",
        "function Label({",
        "  className,",
        "  onPress,",
        "  onLongPress,",
        "  onPressIn,",
        "  onPressOut,",
        "  disabled,",
        "  ...props",
        "}: React.ComponentProps<typeof LabelPrimitive.Text>) {",
        "  return (",
        "    <LabelPrimitive.Root",
        "      className={cn(",
        '        "flex select-none flex-row items-center gap-2",',
        "        Platform.select({",
        '          web: "cursor-default leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-50 group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50",',
        "        }),",
        '        disabled && "opacity-50"',
        "      )}",
        "      onPress={onPress}",
        "      onLongPress={onLongPress}",
        "      onPressIn={onPressIn}",
        "      onPressOut={onPressOut}",
        "      disabled={disabled}",
        "    >",
        "      <LabelPrimitive.Text",
        "        className={cn(",
        '          "text-foreground text-sm font-medium",',
        '          Platform.select({ web: "leading-none" }),',
        "          className",
        "        )}",
        "        {...props}",
        "      />",
        "    </LabelPrimitive.Root>",
        "  );",
        "}",
        "",
        "export { Label };",
        ""
      ),
    },

    // ─── components/ui/card.tsx ──────────────────────────────────────────
    {
      path: "src/components/ui/card.tsx",
      content: lines(
        'import { Text, TextClassContext } from "@/src/components/ui/text";',
        'import { cn } from "@/src/lib/utils";',
        'import { View } from "react-native";',
        "",
        "function Card({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof View> & React.RefAttributes<View>) {",
        "  return (",
        '    <TextClassContext.Provider value="text-card-foreground">',
        "      <View",
        "        className={cn(",
        '          "bg-card border-border flex flex-col gap-6 rounded-xl border py-6 shadow-sm shadow-black/5",',
        "          className",
        "        )}",
        "        {...props}",
        "      />",
        "    </TextClassContext.Provider>",
        "  );",
        "}",
        "",
        "function CardHeader({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof View> & React.RefAttributes<View>) {",
        "  return (",
        '    <View className={cn("flex flex-col gap-1.5 px-6", className)} {...props} />',
        "  );",
        "}",
        "",
        "function CardTitle({",
        "  className,",
        "  ref,",
        "  ...props",
        "}: React.ComponentProps<typeof Text> & React.RefAttributes<typeof Text>) {",
        "  return (",
        "    <Text",
        "      ref={ref}",
        '      role="heading"',
        "      aria-level={3}",
        '      className={cn("font-semibold leading-none", className)}',
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "function CardDescription({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof Text> & React.RefAttributes<typeof Text>) {",
        "  return (",
        '    <Text className={cn("text-muted-foreground text-sm", className)} {...props} />',
        "  );",
        "}",
        "",
        "function CardContent({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof View> & React.RefAttributes<View>) {",
        "  return (",
        '    <View className={cn("px-6", className)} {...props} />',
        "  );",
        "}",
        "",
        "function CardFooter({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof View> & React.RefAttributes<View>) {",
        "  return (",
        '    <View className={cn("flex flex-row items-center px-6", className)} {...props} />',
        "  );",
        "}",
        "",
        "export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle };",
        ""
      ),
    },

    // ─── components/ui/separator.tsx ──────────────────────────────────────
    {
      path: "src/components/ui/separator.tsx",
      content: lines(
        'import { cn } from "@/src/lib/utils";',
        'import * as SeparatorPrimitive from "@rn-primitives/separator";',
        "",
        "function Separator({",
        "  className,",
        '  orientation = "horizontal",',
        "  decorative = true,",
        "  ...props",
        "}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {",
        "  return (",
        "    <SeparatorPrimitive.Root",
        "      decorative={decorative}",
        "      orientation={orientation}",
        "      className={cn(",
        '        "bg-border shrink-0",',
        '        orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]",',
        "        className",
        "      )}",
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "export { Separator };",
        ""
      ),
    },

    // ─── components/ui/alert-dialog.tsx ──────────────────────────────────
    {
      path: "src/components/ui/alert-dialog.tsx",
      content: lines(
        'import { buttonTextVariants, buttonVariants } from "@/src/components/ui/button";',
        'import { TextClassContext } from "@/src/components/ui/text";',
        'import { cn } from "@/src/lib/utils";',
        'import * as AlertDialogPrimitive from "@rn-primitives/alert-dialog";',
        'import * as React from "react";',
        'import { Platform, View, type ViewProps } from "react-native";',
        "",
        "const AlertDialog = AlertDialogPrimitive.Root;",
        "",
        "const AlertDialogTrigger = AlertDialogPrimitive.Trigger;",
        "",
        "const AlertDialogPortal = AlertDialogPrimitive.Portal;",
        "",
        "function AlertDialogOverlay({",
        "  className,",
        "  ...props",
        "}: Omit<React.ComponentProps<typeof AlertDialogPrimitive.Overlay>, \"asChild\"> & {",
        "  children?: React.ReactNode;",
        "}) {",
        "  return (",
        "    <AlertDialogPrimitive.Overlay",
        "      className={cn(",
        '        "absolute bottom-0 left-0 right-0 top-0 z-50 flex items-center justify-center bg-black/50 p-2",',
        "        Platform.select({",
        '          web: "animate-in fade-in-0 fixed",',
        "        }),",
        "        className",
        "      )}",
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "function AlertDialogContent({",
        "  className,",
        "  portalHost,",
        "  ...props",
        "}: React.ComponentProps<typeof AlertDialogPrimitive.Content> & {",
        "  portalHost?: string;",
        "}) {",
        "  return (",
        "    <AlertDialogPortal hostName={portalHost}>",
        "      <AlertDialogOverlay>",
        "        <AlertDialogPrimitive.Content",
        "          className={cn(",
        '            "bg-background border-border z-50 flex w-full max-w-[calc(100%-2rem)] flex-col gap-4 rounded-lg border p-6 shadow-lg shadow-black/5 sm:max-w-lg",',
        "            Platform.select({",
        '              web: "animate-in fade-in-0 zoom-in-95 duration-200",',
        "            }),",
        "            className",
        "          )}",
        "          {...props}",
        "        />",
        "      </AlertDialogOverlay>",
        "    </AlertDialogPortal>",
        "  );",
        "}",
        "",
        "function AlertDialogHeader({ className, ...props }: ViewProps) {",
        "  return (",
        '    <TextClassContext.Provider value="text-center sm:text-left">',
        '      <View className={cn("flex flex-col gap-2", className)} {...props} />',
        "    </TextClassContext.Provider>",
        "  );",
        "}",
        "",
        "function AlertDialogFooter({ className, ...props }: ViewProps) {",
        "  return (",
        '    <View className={cn("flex flex-col-reverse gap-2 sm:flex-row sm:justify-end", className)} {...props} />',
        "  );",
        "}",
        "",
        "function AlertDialogTitle({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof AlertDialogPrimitive.Title>) {",
        "  return (",
        "    <AlertDialogPrimitive.Title",
        '      className={cn("text-foreground text-lg font-semibold", className)}',
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "function AlertDialogDescription({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof AlertDialogPrimitive.Description>) {",
        "  return (",
        "    <AlertDialogPrimitive.Description",
        '      className={cn("text-muted-foreground text-sm", className)}',
        "      {...props}",
        "    />",
        "  );",
        "}",
        "",
        "function AlertDialogAction({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof AlertDialogPrimitive.Action>) {",
        "  return (",
        "    <TextClassContext.Provider value={buttonTextVariants({ className })}>",
        '      <AlertDialogPrimitive.Action className={cn(buttonVariants(), className)} {...props} />',
        "    </TextClassContext.Provider>",
        "  );",
        "}",
        "",
        "function AlertDialogCancel({",
        "  className,",
        "  ...props",
        "}: React.ComponentProps<typeof AlertDialogPrimitive.Cancel>) {",
        "  return (",
        "    <TextClassContext.Provider value={buttonTextVariants({ className, variant: \"outline\" })}>",
        "      <AlertDialogPrimitive.Cancel",
        "          className={cn(buttonVariants({ variant: \"outline\" }), className)} {...props} />",
        "    </TextClassContext.Provider>",
        "  );",
        "}",
        "",
        "export {",
        "  AlertDialog,",
        "  AlertDialogAction,",
        "  AlertDialogCancel,",
        "  AlertDialogContent,",
        "  AlertDialogDescription,",
        "  AlertDialogFooter,",
        "  AlertDialogHeader,",
        "  AlertDialogOverlay,",
        "  AlertDialogPortal,",
        "  AlertDialogTitle,",
        "  AlertDialogTrigger,",
        "};",
        ""
      ),
    },
  ],
};

export default uiReusablesModule;
