import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const uiReusablesModule: ModuleDef = {
  id: "ui-reusables",
  name: "reactnative.reusables UI",
  description: "预置 UI 组件",
  defaultChecked: false,
  dependencies: {
    "reactnative.reusables": "^0.1.0",
    "react-native-svg": "^15.8.0",
    "@rn-primitives/slot": "^1.1.0",
    "@rn-primitives/types": "^1.1.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/components/ui/button.tsx",
      content: lines(
        'import React from "react";',
        'import { Text, Pressable, type PressableProps, type StyleProp, type ViewStyle, type TextStyle } from "react-native";',
        'import { Slot } from "@rn-primitives/slot";',
        "",
        'type ButtonVariant = "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";',
        'type ButtonSize = "default" | "sm" | "lg" | "icon";',
        "",
        "interface ButtonProps extends PressableProps {",
        "  variant?: ButtonVariant;",
        "  size?: ButtonSize;",
        "  asChild?: boolean;",
        "  style?: StyleProp<ViewStyle>;",
        "  textStyle?: StyleProp<TextStyle>;",
        "  children: React.ReactNode;",
        "}",
        "",
        "const variantStyles: Record<ButtonVariant, ViewStyle> = {",
        '  default: { backgroundColor: "#0f172a" },',
        '  destructive: { backgroundColor: "#ef4444" },',
        '  outline: { backgroundColor: "transparent", borderWidth: 1, borderColor: "#d4d4d8" },',
        '  secondary: { backgroundColor: "#f4f4f5" },',
        '  ghost: { backgroundColor: "transparent" },',
        '  link: { backgroundColor: "transparent" },',
        "};",
        "",
        "const variantTextStyles: Record<ButtonVariant, TextStyle> = {",
        '  default: { color: "#fafafa" },',
        '  destructive: { color: "#fafafa" },',
        '  outline: { color: "#18181b" },',
        '  secondary: { color: "#18181b" },',
        '  ghost: { color: "#18181b" },',
        '  link: { color: "#2563eb", textDecorationLine: "underline" },',
        "};",
        "",
        "const sizeStyles: Record<ButtonSize, ViewStyle> = {",
        "  default: { height: 44, paddingHorizontal: 16 },",
        "  sm: { height: 36, paddingHorizontal: 12 },",
        "  lg: { height: 52, paddingHorizontal: 24 },",
        "  icon: { height: 44, width: 44 },",
        "};",
        "",
        "const sizeTextStyles: Record<ButtonSize, TextStyle> = {",
        "  default: { fontSize: 16 },",
        "  sm: { fontSize: 14 },",
        "  lg: { fontSize: 18 },",
        "  icon: { fontSize: 16 },",
        "};",
        "",
        "export function Button({",
        '  variant = "default",',
        '  size = "default",',
        "  asChild = false,",
        "  style,",
        "  textStyle,",
        "  children,",
        "  ...rest",
        "}: ButtonProps) {",
        "  const containerStyle: StyleProp<ViewStyle> = [",
        "    {",
        "      borderRadius: 8,",
        '      flexDirection: "row",',
        '      alignItems: "center",',
        '      justifyContent: "center",',
        "    },",
        "    variantStyles[variant],",
        "    sizeStyles[size],",
        "    style,",
        "  ];",
        "",
        "  const textStyling: StyleProp<TextStyle> = [",
        "    {",
        '      fontWeight: "600",',
        '      textAlign: "center",',
        "    },",
        "    variantTextStyles[variant],",
        "    sizeTextStyles[size],",
        "    textStyle,",
        "  ];",
        "",
        "  if (asChild && React.isValidElement(children)) {",
        "    return (",
        "      <Pressable style={containerStyle} {...rest}>",
        "        <Slot>{children}</Slot>",
        "      </Pressable>",
        "    );",
        "  }",
        "",
        "  return (",
        "    <Pressable style={containerStyle} {...rest}>",
        "      {typeof children === \"string\" ? (",
        "        <Text style={textStyling}>{children}</Text>",
        "      ) : (",
        "        children",
        "      )}",
        "    </Pressable>",
        "  );",
        "}",
        "",
        "export default Button;"
      ),
    },
    {
      path: "src/components/ui/input.tsx",
      content: lines(
        'import React, { forwardRef } from "react";',
        'import {',
        "  TextInput,",
        "  type TextInputProps,",
        "  type StyleProp,",
        "  type ViewStyle,",
        "  type TextStyle,",
        "  View,",
        "  Text,",
        '} from "react-native";',
        "",
        "interface InputProps extends TextInputProps {",
        "  label?: string;",
        "  error?: string;",
        "  containerStyle?: StyleProp<ViewStyle>;",
        "  inputStyle?: StyleProp<TextStyle>;",
        "}",
        "",
        "export const Input = forwardRef<TextInput, InputProps>(",
        "  ({ label, error, containerStyle, inputStyle, ...rest }, ref) => {",
        "    return (",
        "      <View style={containerStyle}>",
        "        {label && <Text style={styles.label}>{label}</Text>}",
        "        <TextInput",
        "          ref={ref}",
        "          style={[",
        "            styles.input,",
        "            error && styles.inputError,",
        "            inputStyle,",
        "          ]}",
        '          placeholderTextColor="#a1a1aa"',
        "          {...rest}",
        "        />",
        "        {error && <Text style={styles.errorText}>{error}</Text>}",
        "      </View>",
        "    );",
        "  }",
        ");",
        "",
        'Input.displayName = "Input";',
        "",
        "const styles = {",
        "  label: {",
        "    fontSize: 14,",
        '    fontWeight: "500",',
        '    color: "#18181b",',
        "    marginBottom: 6,",
        "  } as TextStyle,",
        "  input: {",
        "    height: 44,",
        "    borderWidth: 1,",
        '    borderColor: "#d4d4d8",',
        "    borderRadius: 8,",
        "    paddingHorizontal: 12,",
        "    fontSize: 16,",
        '    color: "#18181b",',
        '    backgroundColor: "#ffffff",',
        "  } as TextStyle,",
        "  inputError: {",
        '    borderColor: "#ef4444",',
        "  } as TextStyle,",
        "  errorText: {",
        "    fontSize: 12,",
        '    color: "#ef4444",',
        "    marginTop: 4,",
        "  } as TextStyle,",
        "};",
        "",
        "export default Input;"
      ),
    },
    {
      path: "src/components/ui/card.tsx",
      content: lines(
        'import React from "react";',
        'import { View, Text, type StyleProp, type ViewStyle, type TextStyle } from "react-native";',
        "",
        "interface CardProps {",
        "  title?: string;",
        "  description?: string;",
        "  children: React.ReactNode;",
        "  style?: StyleProp<ViewStyle>;",
        "  titleStyle?: StyleProp<TextStyle>;",
        "  descriptionStyle?: StyleProp<TextStyle>;",
        '  padding?: "none" | "sm" | "md" | "lg";',
        "}",
        "",
        "const paddingMap: Record<NonNullable<CardProps[\"padding\"]>, number> = {",
        "  none: 0,",
        "  sm: 8,",
        "  md: 16,",
        "  lg: 24,",
        "};",
        "",
        "export function Card({",
        "  title,",
        "  description,",
        "  children,",
        "  style,",
        "  titleStyle,",
        "  descriptionStyle,",
        '  padding = "md",',
        "}: CardProps) {",
        "  return (",
        "    <View",
        "      style={[",
        "        {",
        '          backgroundColor: "#ffffff",',
        "          borderRadius: 12,",
        "          borderWidth: 1,",
        '          borderColor: "#e4e4e7",',
        "          padding: paddingMap[padding],",
        "        },",
        "        style,",
        "      ]}",
        "    >",
        "      {title && (",
        "        <Text style={[styles.title, titleStyle]}>{title}</Text>",
        "      )}",
        "      {description && (",
        "        <Text style={[styles.description, descriptionStyle]}>",
        "          {description}",
        "        </Text>",
        "      )}",
        "      {children}",
        "    </View>",
        "  );",
        "}",
        "",
        "const styles = {",
        "  title: {",
        "    fontSize: 18,",
        '    fontWeight: "600",',
        '    color: "#18181b",',
        "    marginBottom: 4,",
        "  } as TextStyle,",
        "  description: {",
        "    fontSize: 14,",
        '    color: "#71717a",',
        "    marginBottom: 12,",
        "  } as TextStyle,",
        "};",
        "",
        "export default Card;"
      ),
    },
  ],
};

export default uiReusablesModule;
