import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const videoModule: ModuleDef = {
  id: "video",
  name: "视频",
  description: "expo-av 封装",
  defaultChecked: false,
  dependencies: {
    "expo-av": "~15.0.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/media/VideoPlayer.tsx",
      content: lines(
        'import React, { useCallback, useRef, useState } from "react";',
        'import {',
        "  Video,",
        "  ResizeMode,",
        "  type AVPlaybackStatus,",
        "  type VideoProps,",
        '} from "expo-av";',
        'import { StyleSheet, View, TouchableOpacity, ActivityIndicator } from "react-native";',
        "",
        "interface VideoPlayerProps extends Omit<VideoProps, \"source\"> {",
        "  uri: string;",
        "  autoPlay?: boolean;",
        "  loop?: boolean;",
        "  showControls?: boolean;",
        "  width?: number;",
        "  height?: number;",
        "}",
        "",
        "export function VideoPlayer({",
        "  uri,",
        "  autoPlay = false,",
        "  loop = false,",
        "  showControls = true,",
        "  width,",
        "  height,",
        "  style,",
        "  ...rest",
        "}: VideoPlayerProps) {",
        "  const videoRef = useRef<Video>(null);",
        "  const [isPlaying, setIsPlaying] = useState(autoPlay);",
        "  const [isLoading, setIsLoading] = useState(true);",
        "",
        "  const handlePlaybackStatusUpdate = useCallback(",
        "    (status: AVPlaybackStatus) => {",
        "      if (status.isLoaded) {",
        "        setIsLoading(status.isBuffering);",
        "        setIsPlaying(status.isPlaying);",
        "      }",
        "    },",
        "    []",
        "  );",
        "",
        "  const togglePlayback = useCallback(async () => {",
        "    if (!videoRef.current) return;",
        "    if (isPlaying) {",
        "      await videoRef.current.pauseAsync();",
        "    } else {",
        "      await videoRef.current.playAsync();",
        "    }",
        "  }, [isPlaying]);",
        "",
        "  const containerStyle = StyleSheet.compose(",
        '    { width, height, backgroundColor: "#000", borderRadius: 8, overflow: "hidden" },',
        "    style as any",
        "  );",
        "",
        "  return (",
        "    <View style={containerStyle}>",
        "      <Video",
        "        ref={videoRef}",
        "        source={{ uri }}",
        "        style={StyleSheet.absoluteFillObject}",
        "        resizeMode={ResizeMode.CONTAIN}",
        "        shouldPlay={autoPlay}",
        "        isLooping={loop}",
        "        onPlaybackStatusUpdate={handlePlaybackStatusUpdate}",
        "        {...rest}",
        "      />",
        "",
        "      {isLoading && (",
        '        <View style={styles.overlay}>',
        '          <ActivityIndicator color="#fff" size="large" />',
        "        </View>",
        "      )}",
        "",
        "      {showControls && !isLoading && (",
        "        <TouchableOpacity",
        "          style={styles.overlay}",
        "          onPress={togglePlayback}",
        "          activeOpacity={0.7}",
        "        />",
        "      )}",
        "    </View>",
        "  );",
        "}",
        "",
        "const styles = StyleSheet.create({",
        "  overlay: {",
        "    ...StyleSheet.absoluteFillObject,",
        '    justifyContent: "center",',
        '    alignItems: "center",',
        '    backgroundColor: "rgba(0, 0, 0, 0.3)",',
        "  },",
        "});",
        "",
        "export default VideoPlayer;"
      ),
    },
  ],
};

export default videoModule;
