import type { ModuleDef } from "../types";
import { lines } from "../utils/lines";

const webviewModule: ModuleDef = {
  id: "webview",
  name: "WebView 容器",
  description: "react-native-webview + JS Bridge",
  defaultChecked: false,
  dependencies: {
    "react-native-webview": "^13.12.0",
  },
  devDependencies: {},
  files: [
    {
      path: "src/modules/webview/WebViewContainer.tsx",
      content: lines(
        'import React, { useCallback, useRef } from "react";',
        'import { View, StyleSheet, ActivityIndicator } from "react-native";',
        'import WebView, {',
        "  type WebViewMessageEvent,",
        "  type WebViewProps,",
        '} from "react-native-webview";',
        'import { bridge, type BridgeMessage } from "./bridge";',
        "",
        "interface WebViewContainerProps extends Omit<WebViewProps, \"source\"> {",
        "  uri: string;",
        "  showLoading?: boolean;",
        "  onBridgeMessage?: (message: BridgeMessage) => void;",
        "}",
        "",
        "export function WebViewContainer({",
        "  uri,",
        "  showLoading = true,",
        "  onBridgeMessage,",
        "  style,",
        "  ...rest",
        "}: WebViewContainerProps) {",
        "  const webViewRef = useRef<WebView>(null);",
        "",
        "  const handleMessage = useCallback(",
        "    (event: WebViewMessageEvent) => {",
        "      try {",
        "        const data = JSON.parse(event.nativeEvent.data) as BridgeMessage;",
        "        const processed = bridge.receive(data);",
        "        if (onBridgeMessage) {",
        "          onBridgeMessage(processed);",
        "        }",
        "      } catch (error) {",
        '        console.warn("[WebView] Failed to parse message:", error);',
        "      }",
        "    },",
        "    [onBridgeMessage]",
        "  );",
        "",
        "  const sendToWebView = useCallback(",
        "    (message: BridgeMessage) => {",
        "      const script = bridge.buildSendScript(message);",
        "      webViewRef.current?.injectJavaScript(script);",
        "    },",
        "    []",
        "  );",
        "",
        "  const injectedJavaScript = [",
        "    \"(function() {\",",
        "    \"  window.ReactNativeWebView = window.ReactNativeWebView || {};\",",
        "    \"  window.NativeBridge = {\",",
        "    \"    send: function(type, payload) {\",",
        '    "      window.ReactNativeWebView.postMessage(JSON.stringify({ type: type, payload: payload }));",',
        "    \"    }\",\,",
        "    \"  };\,",
        "    \"})();\,",
        "    \"true;\,",
        "  ].join(\"\\\\n\");",
        "",
        "  return (",
        "    <View style={styles.container}>",
        "      <WebView",
        "        ref={webViewRef}",
        "        source={{ uri }}",
        "        style={[styles.webview, style]}",
        '        originWhitelist={["*"]}',
        "        javaScriptEnabled",
        "        domStorageEnabled",
        "        injectedJavaScript={injectedJavaScript}",
        "        onMessage={handleMessage}",
        "        startInLoadingState={showLoading}",
        "        renderLoading={() =>",
        "          showLoading ? (",
        '            <View style={styles.loadingContainer}>',
        '              <ActivityIndicator size="large" color="#007AFF" />',
        "            </View>",
        "          ) : null",
        "        }",
        "        {...rest}",
        "      />",
        "    </View>",
        "  );",
        "}",
        "",
        "const styles = StyleSheet.create({",
        "  container: {",
        "    flex: 1,",
        "  },",
        "  webview: {",
        "    flex: 1,",
        "  },",
        "  loadingContainer: {",
        "    position: \"absolute\",",
        "    top: 0,",
        "    left: 0,",
        "    right: 0,",
        "    bottom: 0,",
        "    justifyContent: \"center\",",
        "    alignItems: \"center\",",
        '    backgroundColor: "rgba(255, 255, 255, 0.8)",',
        "  },",
        "});",
        "",
        "export default WebViewContainer;"
      ),
    },
    {
      path: "src/modules/webview/bridge.ts",
      content: lines(
        "export interface BridgeMessage {",
        "  type: string;",
        "  payload: Record<string, unknown>;",
        "}",
        "",
        "export const BridgeMessageType = {",
        '  NAVIGATE: "NAVIGATE",',
        '  SHARE: "SHARE",',
        '  PAYMENT: "PAYMENT",',
        '  AUTH: "AUTH",',
        '  TOAST: "TOAST",',
        '  CLOSE: "CLOSE",',
        '  CUSTOM: "CUSTOM",',
        "} as const;",
        "",
        "export type BridgeMessageTypeValue =",
        "  (typeof BridgeMessageType)[keyof typeof BridgeMessageType];",
        "",
        "export const bridge = {",
        "  receive(message: BridgeMessage): BridgeMessage {",
        "    if (!message.type) {",
        '      throw new Error("Bridge message must have a \'type\' field");',
        "    }",
        "    return {",
        "      type: message.type,",
        "      payload: message.payload || {},",
        "    };",
        "  },",
        "",
        "  buildSendScript(message: BridgeMessage): string {",
        "    const payload = JSON.stringify(message.payload);",
        "    return [",
        "      \"(function() {\",",
        "      \"  if (typeof window.onNativeMessage === \'function\') {\",",
        "      \"    window.onNativeMessage(\'\" + message.type + \"\', \" + payload + \");\",",
        "      \"  }\",",
        "      \"})();\",",
        "      \"true;\",",
        "    ].join(\"\\\\n\");",
        "  },",
        "",
        "  createMessage(",
        "    type: BridgeMessageTypeValue | string,",
        "    payload: Record<string, unknown> = {}",
        "  ): BridgeMessage {",
        "    return { type, payload };",
        "  },",
        "};"
      ),
    },
  ],
};

export default webviewModule;
